using System.Collections.Generic;
using System.Linq;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.CharacterCreationContent;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.Core;
using TaleWorlds.Localization;

namespace BloodAndBittersteel.Features.CharacterCreation;

/// <summary>
/// Reusable smallfolk and household paths shared across the nine playable
/// Westerosi cultures. Culture classes opt into these lists explicitly.
/// </summary>
public static class WesterosiSharedPathOptions
{
    private static readonly string[] WesterosiCultures =
    {
        "crownlander", "valeman", "stormlander", "dornish", "reachman",
        "westerlander", "riverlander", "ironislander", "northman"
    };

    private static bool IsWesterosi(CharacterCreationManager ccm) => WesterosiCultures.Contains(ccm.CharacterCreationContent.SelectedCulture.StringId);
    private static bool ParentIs(CharacterCreationManager ccm, params string[] occupations) => occupations.Contains(ccm.CharacterCreationContent.SelectedParentOccupation);
    private static bool IsFemale => CharacterObject.PlayerCharacter.IsFemale;
    private static bool IsMale => !CharacterObject.PlayerCharacter.IsFemale;
    private static bool IsRural(CharacterCreationManager ccm) => !CharacterOccupations.IsUrbanOccupation(ccm.CharacterCreationContent.SelectedParentOccupation);
    private static bool IsUrban(CharacterCreationManager ccm) => CharacterOccupations.IsUrbanOccupation(ccm.CharacterCreationContent.SelectedParentOccupation);

    private static void SelectYouth(CharacterCreationManager ccm, string titleType, string animation)
        => NarrativeEquipmentHelper.SelectYouthEquipment(ccm, ccm.CharacterCreationContent.SelectedCulture.StringId, titleType, animation);

    public static IEnumerable<NarrativeOption> YouthOptions
    {
        get
        {
            yield return new NarrativeOption("westerosi_youth_family_farm_option", new TextObject("{=bab_westerosi_youth_family_farm_title}worked the family farm through lean years and harvest feasts."), new TextObject("{=bab_westerosi_youth_family_farm_desc}You worked the family's fields, orchard, or vineyard through lean years and harvest feasts, learning how weather, soil, labour, and careful stores decided whether a household prospered or went hungry."), (args, u) => u.UpgradeAthleticsPolearmSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsWesterosi(ccm) && ParentIs(ccm, CharacterOccupations.Farmer), ccm => SelectYouth(ccm, "farmer", "act_childhood_grit"));
            yield return new NarrativeOption("westerosi_youth_family_workshop_option", new TextObject("{=bab_westerosi_youth_family_workshop_title}helped as an apprentice in the family workshop."), new TextObject("{=bab_westerosi_youth_family_workshop_desc}Whether your family wove cloth, shaped pots, worked timber, made shoes, or practised another humble craft, you learned through repetition, sore hands, and the judgment of paying customers."), (args, u) => u.UpgradeTradeCraftingSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsWesterosi(ccm) && ParentIs(ccm, CharacterOccupations.ArtisanUrban), ccm => SelectYouth(ccm, "craftman", "act_childhood_grit"));
            yield return new NarrativeOption("westerosi_youth_noble_servant_option", new TextObject("{=bab_westerosi_youth_noble_servant_title}entered service in a noble household."), new TextObject("{=bab_westerosi_youth_noble_servant_desc}You found a place as a maid, attendant, kitchen servant, or chamber helper. The work was tiring, but it taught you how a great household truly functioned and what its highborn inhabitants said when they thought servants invisible."), (args, u) => u.UpgradeStewardCharmSkills(args, DefaultCharacterAttributes.Social), ccm => IsWesterosi(ccm) && IsFemale && !ParentIs(ccm, CharacterOccupations.Retainer), ccm => SelectYouth(ccm, "guard", "act_childhood_manners"));
            yield return new NarrativeOption("westerosi_youth_road_wanderer_option", new TextObject("{=bab_westerosi_youth_road_wanderer_title}left home and wandered the roads for work."), new TextObject("{=bab_westerosi_youth_road_wanderer_desc}After a hard winter or failed harvest, you left home, took day-work wherever it was offered, and slept in barns, ditches, or beneath hedges when no kinder shelter could be found."), (args, u) => u.UpgradeAthleticsRoguerySkills(args, DefaultCharacterAttributes.Endurance), ccm => IsWesterosi(ccm) && ParentIs(ccm, CharacterOccupations.Farmer, CharacterOccupations.Hunter), ccm => SelectYouth(ccm, "bandit", "act_childhood_peddlers"));
            yield return new NarrativeOption("westerosi_youth_caravan_hand_option", new TextObject("{=bab_westerosi_youth_caravan_hand_title}worked as a caravan hand."), new TextObject("{=bab_westerosi_youth_caravan_hand_desc}You loaded wagons, tended pack animals, bargained for fodder, and learned which roads, ferries, inns, and guards could be trusted."), (args, u) => u.UpgradeTradeTacticsSkills(args, DefaultCharacterAttributes.Cunning), ccm => IsWesterosi(ccm) && ParentIs(ccm, CharacterOccupations.MerchantUrban, CharacterOccupations.Farmer, CharacterOccupations.Hunter), ccm => SelectYouth(ccm, "merchant", "act_childhood_peddlers_2"));
            yield return new NarrativeOption("westerosi_youth_household_clerk_option", new TextObject("{=bab_westerosi_youth_household_clerk_title}kept records for a household or counting room."), new TextObject("{=bab_westerosi_youth_household_clerk_desc}Your letters and sums earned you work copying orders, recording stores, checking payments, and discovering how easily a careless mark could become a costly mistake."), (args, u) => u.UpgradeEngineeringTradeSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsWesterosi(ccm) && ParentIs(ccm, CharacterOccupations.Retainer, CharacterOccupations.MerchantUrban), ccm => SelectYouth(ccm, "merchant", "act_childhood_book"));
            yield return new NarrativeOption("westerosi_youth_stable_hand_option", new TextObject("{=bab_westerosi_youth_stable_hand_title}worked as a stable hand and drover's helper."), new TextObject("{=bab_westerosi_youth_stable_hand_desc}You groomed horses, tended sick animals, moved stubborn stock, and learned to judge both beasts and the people who bought them."), (args, u) => u.UpgradeRidingStewardSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsWesterosi(ccm) && ParentIs(ccm, CharacterOccupations.Retainer, CharacterOccupations.Farmer, CharacterOccupations.Hunter), ccm => SelectYouth(ccm, "cavalry", "act_childhood_animals"));
            yield return new NarrativeOption("westerosi_youth_poacher_option", new TextObject("{=bab_westerosi_youth_poacher_title}turned poacher in the lord's woods."), new TextObject("{=bab_westerosi_youth_poacher_desc}When taxes or hunger grew too heavy, you learned to take deer, rabbits, and birds without attracting the foresters, trusting quiet feet and intimate knowledge of every game trail."), (args, u) => u.UpgradeScoutingBowSkills(args, DefaultCharacterAttributes.Cunning), ccm => IsWesterosi(ccm) && ParentIs(ccm, CharacterOccupations.Farmer, CharacterOccupations.Hunter), ccm => SelectYouth(ccm, "skirmisher", "act_childhood_fox"));
            yield return new NarrativeOption("westerosi_youth_itinerant_craft_option", new TextObject("{=bab_westerosi_youth_itinerant_craft_title}travelled from holding to holding repairing what others could not."), new TextObject("{=bab_westerosi_youth_itinerant_craft_desc}You carried a small kit of tools between villages, repairing carts, roofs, shoes, pots, tools, and household goods in return for coin, meals, or a bed near the hearth."), (args, u) => u.UpgradeTradeCraftingSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsWesterosi(ccm) && ParentIs(ccm, CharacterOccupations.ArtisanUrban), ccm => SelectYouth(ccm, "craftman", "act_childhood_grit"));
            yield return new NarrativeOption("youth_groom_option", new TextObject("{=bab_westerosi_youth_groom_title}served as a lord's groom."), new TextObject("{=bab_westerosi_youth_groom_desc}You accompanied a landed knight in the service of a Westerosi lord. You were not given major responsibilities, mostly carrying messages and tending to his horse, but it gave you a chance to see how campaigns were planned and men were deployed in battle."), (args, u) => u.UpgradeCharmTacticsSkills(args, DefaultCharacterAttributes.Social), ccm => IsWesterosi(ccm) && !IsFemale && ParentIs(ccm, CharacterOccupations.Retainer), ccm => SelectYouth(ccm, "noble", "act_childhood_sharp"));
            yield return new NarrativeOption("youth_cavalry_option", new TextObject("{=bab_westerosi_youth_cavalry_title}trained with the cavalry."), new TextObject("{=bab_westerosi_youth_cavalry_desc}You could never have bought the equipment on your own, but you were a good enough rider so that the local lord lent you a horse and equipment. You joined the armored cavalry, training with the lance."), (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsWesterosi(ccm) && !IsFemale && ParentIs(ccm, CharacterOccupations.Retainer, CharacterOccupations.Farmer, CharacterOccupations.Hunter), ccm => SelectYouth(ccm, "cavalry", "act_childhood_apprentice"));
            yield return new NarrativeOption("youth_guard_high_register_option", new TextObject("{=bab_westerosi_youth_guard_title}stood guard with the garrisons."), new TextObject("{=bab_westerosi_youth_guard_desc}The towns and castles of the realm always needed watchmen. You learned to patrol walls, keep order at the gates, and defend the battlements in time of siege."), (args, u) => u.UpgradeCrossbowEngineeringSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsWesterosi(ccm) && ParentIs(ccm, CharacterOccupations.Retainer, CharacterOccupations.MerchantUrban, CharacterOccupations.ArtisanUrban), ccm => SelectYouth(ccm, "guard", "act_childhood_vibrant"));
            yield return new NarrativeOption("youth_infantry_option", new TextObject("{=bab_westerosi_youth_infantry_title}trained with the infantry."), new TextObject("{=bab_westerosi_youth_infantry_desc}Levy armed with spear and shield, drawn from smallholding farmers, have always been the backbone of most armies in the realm."), (args, u) => u.UpgradePolearmOneHandedSkills(args, DefaultCharacterAttributes.Vigor), ccm => IsWesterosi(ccm) && !IsFemale && ParentIs(ccm, CharacterOccupations.Farmer, CharacterOccupations.ArtisanUrban), ccm => SelectYouth(ccm, "infantry", "act_childhood_fierce"));
            yield return new NarrativeOption("youth_skirmisher_option", new TextObject("{=bab_westerosi_youth_skirmisher_title}joined the skirmishers."), new TextObject("{=bab_westerosi_youth_skirmisher_desc}Younger recruits, or those of a slighter build, or those too poor to buy shield and armor tend to join the skirmishers. Fighting with bow and javelin, they try to stay out of reach of the main enemy forces."), (args, u) => u.UpgradeThrowingOneHandedSkills(args, DefaultCharacterAttributes.Control), ccm => IsWesterosi(ccm) && ParentIs(ccm, CharacterOccupations.Farmer, CharacterOccupations.Hunter), ccm => SelectYouth(ccm, "skirmisher", "act_childhood_fox"));
            yield return new NarrativeOption("youth_bandit_option", new TextObject("{=bab_westerosi_youth_bandit_title}ran with an outlaw band."), new TextObject("{=bab_westerosi_youth_bandit_desc}You fell in with poachers, smugglers, and broken men who haunted the roads and forests. You learned to move unseen, survive by your wits, and strike before anyone could raise the alarm."), (args, u) => u.UpgradeRogueryThrowingSkills(args, DefaultCharacterAttributes.Cunning), ccm => IsWesterosi(ccm) && ParentIs(ccm, CharacterOccupations.Farmer, CharacterOccupations.Hunter), ccm => SelectYouth(ccm, "bandit", "act_childhood_militia"));
            yield return new NarrativeOption("youth_camp_option", new TextObject("{=bab_westerosi_youth_camp_title}marched with the camp followers."), new TextObject("{=bab_westerosi_youth_camp_desc}You avoided service with one of the main forces of your realm's armies, but followed instead in the train: the troops' wives, lovers and servants, and those who make their living by caring for, entertaining, or cheating the soldiery."), (args, u) => u.UpgradeRogueryThrowingSkills(args, DefaultCharacterAttributes.Cunning), ccm => IsWesterosi(ccm) && ParentIs(ccm, CharacterOccupations.MerchantUrban, CharacterOccupations.Farmer, CharacterOccupations.Hunter), ccm => SelectYouth(ccm, "bard", "act_childhood_militia"));
        }
    }

    public static IEnumerable<NarrativeOption> AdulthoodOptions
    {
        get
        {
            yield return new NarrativeOption("westerosi_adulthood_rebuilt_option", new TextObject("{=bab_westerosi_adulthood_rebuilt_title}you rebuilt after disaster took almost everything."), new TextObject("{=bab_westerosi_adulthood_rebuilt_desc}Fire, flood, storm, or failed harvest wiped out what little you had. You rebuilt with salvaged tools, borrowed labour, and the lesson never again to trust a single season."), (args, u) => { u.UpgradeLeadershipStewardSkills(args, DefaultCharacterAttributes.Endurance); args.SetRenownToAdd(5); }, ccm => IsWesterosi(ccm) && !ParentIs(ccm, CharacterOccupations.Retainer), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_grit"));
            yield return new NarrativeOption("westerosi_adulthood_cheated_option", new TextObject("{=bab_westerosi_adulthood_cheated_title}you started again after a partner cheated you."), new TextObject("{=bab_westerosi_adulthood_cheated_desc}A partner or relative took more than their share and left you with the debt. You began again with less coin, harder eyes, and a much sharper understanding of promises and accounts."), (args, u) => { u.UpgradeTradeTacticsSkills(args, DefaultCharacterAttributes.Cunning); args.SetRenownToAdd(5); }, ccm => IsWesterosi(ccm), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_clever"));
            yield return new NarrativeOption("westerosi_adulthood_hired_sword_option", new TextObject("{=bab_westerosi_adulthood_hired_sword_title}you took service as a hired sword or caravan guard."), new TextObject("{=bab_westerosi_adulthood_hired_sword_desc}You learned which roads were worth the risk, which employers paid in silver rather than promises, and when a guarded wagon was not worth dying beside."), (args, u) => { u.UpgradeTradeTacticsSkills(args, DefaultCharacterAttributes.Vigor); args.SetRenownToAdd(10); }, ccm => IsWesterosi(ccm) && IsMale && NarrativeChoiceState.YouthWas("westerosi_youth_caravan_hand_option", "westerosi_youth_road_wanderer_option", "westerosi_youth_stable_hand_option", "crownlander_youth_squire_option", "valeman_youth_squire_option", "stormlander_youth_squire_option", "reachman_youth_squire_option", "westerlander_youth_squire_option", "riverlander_youth_squire_option", "northman_youth_hall_retainer_option", "northman_youth_levy_option", "ironislander_youth_crew_option", "dornish_youth_spear_option"), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_drafted_to_war_pose"));
            yield return new NarrativeOption("westerosi_adulthood_mummer_troupe_option", new TextObject("{=bab_westerosi_adulthood_mummer_troupe_title}you ran a travelling troupe of mummers and singers."), new TextObject("{=bab_westerosi_adulthood_mummer_troupe_desc}You negotiated with innkeepers, dodged hostile septons and suspicious reeves, settled quarrels among performers, and kept the company fed on applause and thin coin."), (args, u) => { u.UpgradeLeadershipCharmSkills(args, DefaultCharacterAttributes.Social); args.SetRenownToAdd(10); }, ccm => IsWesterosi(ccm) && IsFemale && !ParentIs(ccm, CharacterOccupations.Retainer) && NarrativeChoiceState.YouthWas("westerosi_youth_noble_servant_option", "westerosi_youth_road_wanderer_option", "westerosi_youth_caravan_hand_option", "westerosi_youth_itinerant_craft_option", "crownlander_youth_gutters_option"), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_manners"));
            yield return new NarrativeOption("westerosi_adulthood_trapper_option", new TextObject("{=bab_westerosi_adulthood_trapper_title}you lived by hunting, trapping, and gathering."), new TextObject("{=bab_westerosi_adulthood_trapper_desc}You survived on the edge of settled land and traded skins, meat, herbs, and honey for salt, iron, cloth, and whatever else could not be taken from the wild."), (args, u) => { u.UpgradeMedicineScoutingSkills(args, DefaultCharacterAttributes.Endurance); args.SetRenownToAdd(5); }, ccm => IsWesterosi(ccm) && ParentIs(ccm, CharacterOccupations.Farmer, CharacterOccupations.Hunter), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_tough"));
            yield return new NarrativeOption("westerosi_adulthood_poacher_option", new TextObject("{=bab_westerosi_adulthood_poacher_title}you lived as a poacher in the lord's woods."), new TextObject("{=bab_westerosi_adulthood_poacher_desc}When taxes and hunger grew too heavy, you lived from stolen deer and the quiet knowledge of every game trail, always listening for foresters and their hounds."), (args, u) => { u.UpgradeScoutingBowSkills(args, DefaultCharacterAttributes.Cunning); args.SetRenownToAdd(5); }, ccm => IsWesterosi(ccm) && NarrativeChoiceState.YouthWas("westerosi_youth_poacher_option"), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_fox"));
            yield return new NarrativeOption("westerosi_adulthood_free_outlaw_option", new TextObject("{=bab_westerosi_adulthood_free_outlaw_title}you took to the woods after trouble in the village."), new TextObject("{=bab_westerosi_adulthood_free_outlaw_desc}A feud, false accusation, unpaid tax, or simple desire for freedom drove you beyond the reach of the village reeve. You survived by your own rules and chose carefully whom to trust."), (args, u) => { u.UpgradeAthleticsRoguerySkills(args, DefaultCharacterAttributes.Cunning); args.SetRenownToAdd(5); }, ccm => IsWesterosi(ccm) && NarrativeChoiceState.YouthWas("westerosi_youth_road_wanderer_option", "westerosi_youth_poacher_option"), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_clever"));
            yield return new NarrativeOption("westerosi_adulthood_drover_option", new TextObject("{=bab_westerosi_adulthood_drover_title}you hired out as a drover and ox-handler."), new TextObject("{=bab_westerosi_adulthood_drover_desc}You moved herds between villages and markets, learning every track cattle could walk and how to keep animals, hired hands, and impatient buyers moving together."), (args, u) => { u.UpgradeRidingStewardSkills(args, DefaultCharacterAttributes.Endurance); args.SetRenownToAdd(5); }, ccm => IsWesterosi(ccm) && IsMale && ParentIs(ccm, CharacterOccupations.Farmer, CharacterOccupations.Hunter, CharacterOccupations.MerchantUrban), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_animals"));
            yield return new NarrativeOption("westerosi_adulthood_midwife_option", new TextObject("{=bab_westerosi_adulthood_midwife_title}you wandered from village to village as a healer and midwife."), new TextObject("{=bab_westerosi_adulthood_midwife_desc}You were welcomed wherever illness or childbirth brought fear, then moved on when the work ended or a jealous local wise-woman made it clear you had stayed too long."), (args, u) => { u.UpgradeMedicineCharmSkills(args, DefaultCharacterAttributes.Social); args.SetRenownToAdd(10); }, ccm => IsWesterosi(ccm) && IsFemale && (ParentIs(ccm, CharacterOccupations.Farmer, CharacterOccupations.Hunter) || NarrativeChoiceState.EducationWas("education_hunter_herbs_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_manners"));
            yield return new NarrativeOption("westerosi_adulthood_outlaw_band_option", new TextObject("{=bab_westerosi_adulthood_outlaw_band_title}you fell in with a band of road outlaws."), new TextObject("{=bab_westerosi_adulthood_outlaw_band_desc}You preyed on lonely roads and poorly guarded pack trains, taking only what could be carried and disappearing before the next patrol reached the district."), (args, u) => { u.UpgradeRogueryTacticsSkills(args, DefaultCharacterAttributes.Cunning); args.SetRenownToAdd(10); }, ccm => IsWesterosi(ccm) && NarrativeChoiceState.YouthWas("westerosi_youth_road_wanderer_option", "westerosi_youth_poacher_option"), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_clever"));
            yield return new NarrativeOption("westerosi_adulthood_household_trust_option", new TextObject("{=bab_westerosi_adulthood_household_trust_title}you became indispensable to a great household."), new TextObject("{=bab_westerosi_adulthood_household_trust_desc}You learned where every key, account, favour, and grievance belonged. When the household faced disorder, your quiet competence kept servants working and dependants loyal."), (args, u) => { u.UpgradeLeadershipStewardSkills(args, DefaultCharacterAttributes.Social); args.SetRenownToAdd(10); }, ccm => IsWesterosi(ccm) && ParentIs(ccm, CharacterOccupations.Retainer), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_manners"));
            yield return new NarrativeOption("westerosi_adulthood_local_reputation_option", new TextObject("{=bab_westerosi_adulthood_local_reputation_title}you became someone your neighbors relied upon."), new TextObject("{=bab_westerosi_adulthood_local_reputation_desc}The skills of your youth made you useful in every difficult season. You settled small quarrels, organized shared work, and earned a reputation for keeping your word when others needed help."), (args, u) => { u.UpgradeStewardCharmSkills(args, DefaultCharacterAttributes.Social); args.SetRenownToAdd(5); }, ccm => IsWesterosi(ccm) && !string.IsNullOrEmpty(NarrativeChoiceState.YouthOptionId), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_manners"));
            yield return new NarrativeOption("westerosi_adulthood_harvest_follower_option", new TextObject("{=bab_westerosi_adulthood_harvest_follower_title}you followed the harvest from one lord's fields to the next."), new TextObject("{=bab_westerosi_adulthood_harvest_follower_desc}You slept in barns or beneath the open sky with other landless hands, owning nothing you could not carry and learning which estates paid fairly when the grain came in."), (args, u) => { u.UpgradeAthleticsTradeSkills(args, DefaultCharacterAttributes.Endurance); args.SetRenownToAdd(5); }, ccm => IsWesterosi(ccm) && ParentIs(ccm, CharacterOccupations.Farmer) && new[] { "crownlander", "reachman", "westerlander" }.Contains(ccm.CharacterCreationContent.SelectedCulture.StringId), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_peddlers"));
            yield return new NarrativeOption("adulthood_defeated_enemy_option", new TextObject("{=8bwpVpgy}you defeated an enemy in battle."), new TextObject("{=1IEroJKs}Not everyone who musters for the levy marches to war, and not everyone who goes on campaign sees action. You did both, and you also took down an enemy warrior in direct one-to-one combat, in the full view of your comrades."), (args, u) =>
            {
                u.UpgradeOneHandedTwoHandedSkills(args, DefaultCharacterAttributes.Vigor);
                args.SetAffectedTraits(new[] { DefaultTraits.Valor });
                args.SetLevelToTraits(1);
                args.SetRenownToAdd(20);
            }, ccm => IsWesterosi(ccm) && !IsFemale && NarrativeChoiceState.YouthWas("youth_groom_option", "youth_cavalry_option", "youth_guard_high_register_option", "youth_infantry_option", "youth_skirmisher_option"), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_athlete"));
            yield return new NarrativeOption("adulthood_manhunt_option", new TextObject("{=mP3uFbcq}you led a successful manhunt."), new TextObject("{=4f5xwzX0}When your community needed to organize a posse to pursue horse thieves, you were the obvious choice. You hunted down the raiders, surrounded them and forced their surrender, and took back your stolen property."), (args, u) =>
            {
                u.UpgradeStewardTacticsSkills(args, DefaultCharacterAttributes.Cunning);
                args.SetAffectedTraits(new[] { DefaultTraits.Calculating });
                args.SetLevelToTraits(1);
                args.SetRenownToAdd(10);
            }, ccm => IsWesterosi(ccm) && !IsFemale && IsRural(ccm)
                && (NarrativeChoiceState.EducationWas("education_hunter_tracking_option", "education_hunter_traps_option") || NarrativeChoiceState.YouthWas("youth_skirmisher_option", "youth_infantry_option")),
                ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_battania_mp_clan_warrior_shieldperk_idle"));
            yield return new NarrativeOption("adulthood_caravan_leader_option", new TextObject("{=wfbtS71d}you led a caravan."), new TextObject("{=joRHKCkm}Your family needed someone trustworthy to take a caravan to a neighboring town. You organized supplies, ensured a constant watch to keep away bandits, and brought it safely to its destination."), (args, u) =>
            {
                u.UpgradeTradeLeadershipSkills(args, DefaultCharacterAttributes.Cunning);
                args.SetAffectedTraits(new[] { DefaultTraits.Calculating });
                args.SetLevelToTraits(1);
                args.SetRenownToAdd(10);
            }, ccm => IsWesterosi(ccm) && IsUrban(ccm)
                && (ParentIs(ccm, CharacterOccupations.MerchantUrban) || NarrativeChoiceState.EducationWas("education_merchant_accounts_option", "education_merchant_market_option", "education_merchant_caravan_option") || NarrativeChoiceState.YouthWas("youth_camp_option")),
                ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_ready_handshield"));
            yield return new NarrativeOption("adulthood_saved_village_option", new TextObject("{=x1HTX5hq}you saved your village from a flood."), new TextObject("{=bWlmGDf3}When a sudden storm caused the local stream to rise suddenly, your neighbors needed quick-thinking leadership. You provided it, directing them to build levees to save their homes."), (args, u) =>
            {
                u.UpgradeStewardTacticsSkills(args, DefaultCharacterAttributes.Cunning);
                args.SetAffectedTraits(new[] { DefaultTraits.Valor });
                args.SetLevelToTraits(1);
                args.SetRenownToAdd(10);
            }, ccm => IsWesterosi(ccm) && IsRural(ccm)
                && (NarrativeChoiceState.EducationWas("education_farmer_fields_option", "education_farmer_herder_option") || NarrativeChoiceState.YouthWas("youth_infantry_option", "youth_camp_option")),
                ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_drafted_to_war_pose"));
            yield return new NarrativeOption("adulthood_workshop_option", new TextObject("{=xORjDTal}you invested some money in a workshop."), new TextObject("{=PyVqDLBu}Your parents didn't give you much money, but they did leave just enough for you to secure a loan against a larger amount to build a small workshop. You paid back what you borrowed, and sold your enterprise for a profit."), (args, u) =>
            {
                u.UpgradeTradeCraftingSkills(args, DefaultCharacterAttributes.Intelligence);
                args.SetAffectedTraits(new[] { DefaultTraits.Calculating });
                args.SetLevelToTraits(1);
                args.SetRenownToAdd(10);
            }, ccm => IsWesterosi(ccm) && IsUrban(ccm) && (ParentIs(ccm, CharacterOccupations.ArtisanUrban) || NarrativeChoiceState.EducationWas("education_artisan_workshop_option", "education_artisan_master_option", "education_artisan_guild_option")),
                ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_decisive"));
            yield return new NarrativeOption("adulthood_investor_option", new TextObject("{=xKXcqRJI}you invested some money in land."), new TextObject("{=cbF9jdQo}Your parents didn't give you much money, but they did leave just enough for you to purchase a plot of unused land at the edge of the village. You cleared away rocks and dug an irrigation ditch, raised a few seasons of crops, than sold it for a considerable profit."), (args, u) =>
            {
                u.UpgradeTradeCraftingSkills(args, DefaultCharacterAttributes.Intelligence);
                args.SetAffectedTraits(new[] { DefaultTraits.Calculating });
                args.SetLevelToTraits(1);
                args.SetRenownToAdd(10);
            }, ccm => IsWesterosi(ccm) && IsRural(ccm) && (ParentIs(ccm, CharacterOccupations.Farmer) || NarrativeChoiceState.EducationWas("education_farmer_fields_option", "education_farmer_market_option")),
                ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_decisive"));
            yield return new NarrativeOption("adulthood_hunter_option", new TextObject("{=TbNRtUjb}you hunted a dangerous animal."), new TextObject("{=I3PcdaaL}Wolves, bears are a constant menace to the flocks of northern lands, while hyenas and leopards trouble the south. You went with a group of your fellow villagers and fired the missile that brought down the beast."), (args, u) =>
            {
                u.UpgradePolearmAthleticsSkills(args, DefaultCharacterAttributes.Control);
                args.SetAffectedTraits(new[] { DefaultTraits.Valor });
                args.SetLevelToTraits(1);
                args.SetRenownToAdd(5);
            }, ccm => IsWesterosi(ccm) && IsRural(ccm) && (ParentIs(ccm, CharacterOccupations.Hunter) || NarrativeChoiceState.EducationWas("education_hunter_tracking_option", "education_hunter_traps_option", "education_hunter_herbs_option")),
                ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_tough"));
            yield return new NarrativeOption("adulthood_siege_survivor_option", new TextObject("{=WbHfGCbd}you survived a siege."), new TextObject("{=FhZPjhli}Your hometown was briefly placed under siege, and you were called to defend the walls. Everyone did their part to repulse the enemy assault, and everyone is justly proud of what they endured."), (args, u) =>
            {
                u.UpgradeBowCrossbowSkills(args, DefaultCharacterAttributes.Control);
                args.SetRenownToAdd(5);
            }, ccm => IsWesterosi(ccm) && !IsFemale && IsUrban(ccm) && NarrativeChoiceState.YouthWas("youth_guard_high_register_option", "youth_infantry_option", "youth_skirmisher_option"),
                ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_tough"));
            yield return new NarrativeOption("adulthood_escapade_high_register_option", new TextObject("{=kNXet6Um}you had a famous escapade in town."), new TextObject("{=DjeAJtix}Maybe it was a love affair, or maybe you cheated at dice, or maybe you just chose your words poorly when drinking with a dangerous crowd. Anyway, on one of your trips into town you got into the kind of trouble from which only a quick tongue or quick feet get you out alive."), (args, u) =>
            {
                u.UpgradeAthleticsRoguerySkills(args, DefaultCharacterAttributes.Endurance);
                args.SetAffectedTraits(new[] { DefaultTraits.Valor });
                args.SetLevelToTraits(1);
                args.SetRenownToAdd(5);
            }, ccm => IsWesterosi(ccm) && IsRural(ccm) && NarrativeChoiceState.YouthWas("youth_skirmisher_option", "youth_camp_option", "youth_infantry_option"),
                ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_clever"));
            yield return new NarrativeOption("adulthood_escapade_low_register_option", new TextObject("{=qlOuiKXj}you had a famous escapade."), new TextObject("{=lD5Ob3R4}Maybe it was a love affair, or maybe you cheated at dice, or maybe you just chose your words poorly when drinking with a dangerous crowd. Anyway, you got into the kind of trouble from which only a quick tongue or quick feet get you out alive."), (args, u) =>
            {
                u.UpgradeAthleticsRoguerySkills(args, DefaultCharacterAttributes.Endurance);
                args.SetAffectedTraits(new[] { DefaultTraits.Valor });
                args.SetLevelToTraits(1);
                args.SetRenownToAdd(5);
            }, ccm => IsWesterosi(ccm) && IsUrban(ccm) && NarrativeChoiceState.YouthWas("youth_camp_option", "youth_guard_high_register_option", "youth_groom_option"),
                ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_clever"));
            yield return new NarrativeOption("adulthood_nice_person_option", new TextObject("{=Yqm0Dics}you treated people well."), new TextObject("{=dDmcqTzb}Yours wasn't the kind of reputation that local legends are made of, but it was the kind that wins you respect among those around you. You were consistently fair and honest in your business dealings and helpful to those in trouble. In doing so, you got a sense of what made people tick."), (args, u) =>
            {
                u.UpgradeStewardCharmSkills(args, DefaultCharacterAttributes.Social);
                args.SetAffectedTraits(new[] { DefaultTraits.Mercy, DefaultTraits.Generosity, DefaultTraits.Honor });
                args.SetLevelToTraits(1);
                args.SetRenownToAdd(5);
            }, ccm => IsWesterosi(ccm) && (NarrativeChoiceState.ChildhoodWas("childhood_leadership_option", "childhood_leader_option") || NarrativeChoiceState.EducationWas("education_merchant_accounts_option", "education_merchant_market_option", "education_hunter_herbs_option", "education_retainer_tutor_option") || NarrativeChoiceState.YouthWas("youth_camp_option", "youth_guard_high_register_option", "youth_groom_option")),
                ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_manners"));
        }
    }
}
