using System.Collections.Generic;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.CharacterCreationContent;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.Core;
using TaleWorlds.Localization;

namespace BloodAndBittersteel.Features.CharacterCreation.Cultures;

public class CrownlanderCulture : ICharacterCreationCulture
{
    public string CultureId => "crownlander";

    public IEnumerable<NarrativeOption> GetParentOptions()
    {
        yield return CreateParentOption("crownlander_retainer_option", "{=bab_crownlander_parent_retainer_title}A lord's retainers", "{=bab_crownlander_parent_retainer_desc}Your family served in the household of a Crownlands lord. They managed his lands, settled disputes among his smallfolk, and trained the local levy. When called to war, they rode beneath his banner.", (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Social), CharacterOccupations.Retainer, "act_character_creation_female_default_side_to_side_1", "act_character_creation_male_default_side_to_side_1");
        yield return CreateParentOption("crownlander_merchant_option", "{=651FhzdR}Urban merchants", "{=bab_crownlander_parent_merchant_desc}Your family were merchants in one of the busy towns of the Crownlands. They organized caravans, dealt with ships and traders from across the narrow sea, and were active in the local merchants' guild.", (args, u) => u.UpgradeTradeCharmSkills(args, DefaultCharacterAttributes.Intelligence), CharacterOccupations.MerchantUrban, "act_character_creation_female_default_mother_front", "act_character_creation_male_default_mother_front");
        yield return CreateParentOption("crownlander_farmer_option", "{=RDfXuVxT}Yeomen", "{=bab_crownlander_parent_farmer_desc}Your family were free smallholders with enough land to feed themselves and sell a modest surplus. They were pillars of the local economy and formed the backbone of their lord's levy.", (args, u) => u.UpgradePolearmCrossbowSkills(args, DefaultCharacterAttributes.Endurance), CharacterOccupations.Farmer, "act_character_creation_female_default_father_sitting", "act_character_creation_male_default_father_sitting");
        yield return CreateParentOption("crownlander_blacksmith_option", "{=p2KIhGbE}Urban blacksmith", "{=bab_crownlander_parent_blacksmith_desc}Your family owned a smithy in a Crownlands town. Your father played a small part in the town's affairs and served with the watch when danger threatened.", (args, u) => u.UpgradeCraftingTwoHandedSkills(args, DefaultCharacterAttributes.Vigor), CharacterOccupations.ArtisanUrban, "act_character_creation_female_default_side_to_side_2", "act_character_creation_male_default_side_to_side_2");
        yield return CreateParentOption("crownlander_hunter_option", "{=YcnK0Thk}Hunters", "{=bab_crownlander_parent_hunter_desc}Your family lived in a village but owned little land. Your father supplemented paid work with long trips through the kingswood, hunting and trapping while keeping a wary eye out for the royal foresters.", (args, u) => u.UpgradeScoutingCrossbowSkills(args, DefaultCharacterAttributes.Control), CharacterOccupations.Hunter, "act_character_creation_female_default_side_to_side_3", "act_character_creation_male_default_side_to_side_3");
    }

    public IEnumerable<NarrativeOption> GetChildhoodOptions()
    {
        foreach (NarrativeOption option in MainlandChildhoodOptions.Shared)
            yield return option;

        yield return new NarrativeOption("crownlander_childhood_court_rumours_option", new TextObject("{=bab_crownlander_childhood_court_rumours_title}listened at the edge of the great halls."), new TextObject("{=bab_crownlander_childhood_court_rumours_desc}While your elders worked, you learned to recognize banners, offices, and the careful words used by petitioners seeking favour from Crownlands lords."), (args, u) => u.UpgradeLeadershipCharmSkills(args, DefaultCharacterAttributes.Social), ccm => IsCrownlander(ccm), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_childhood_character", "act_childhood_manners"));
    }

    public IEnumerable<NarrativeOption> GetEducationOptions()
    {
        foreach (NarrativeOption option in MainlandEducationOptions.Shared)
            yield return option;

        yield return new NarrativeOption("crownlander_education_court_page_option", new TextObject("{=bab_crownlander_education_court_page_title}served as a page at the royal court."), new TextObject("{=bab_crownlander_education_court_page_desc}Your family secured you a place in a Crownlands lord's household near the royal court. You carried messages, attended ceremonies, and watched petitioners and councillors bargain for favour."), (args, u) => u.UpgradeLeadershipTacticsSkills(args, DefaultCharacterAttributes.Social), ccm => IsCrownlander(ccm) && ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer && !CharacterObject.PlayerCharacter.IsFemale, ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_manners", "", ""));
        yield return new NarrativeOption("crownlander_education_court_lady_option", new TextObject("{=bab_crownlander_education_court_lady_title}served as a lady-in-waiting at court."), new TextObject("{=bab_crownlander_education_court_lady_desc}You attended a noblewoman at court, learning proper conduct, household management, correspondence, and the quiet exchange of influence among the ladies of the realm."), (args, u) => u.UpgradeStewardCharmSkills(args, DefaultCharacterAttributes.Social), ccm => IsCrownlander(ccm) && ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer && CharacterObject.PlayerCharacter.IsFemale, ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_manners", "", ""));
        yield return new NarrativeOption("crownlander_education_city_guilds_option", new TextObject("{=bab_crownlander_education_city_guilds_title}learned among the city guilds."), new TextObject("{=bab_crownlander_education_city_guilds_desc}Your family sent you among guild masters, factors, and dockside agents, where you learned how royal taxes, foreign cargoes, and guild privileges shaped trade in the Crownlands."), (args, u) => u.UpgradeTradeCharmSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsCrownlander(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.MerchantUrban || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban), ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_book", "", ""));
    }

    public IEnumerable<NarrativeOption> GetYouthOptions()
    {
        foreach (NarrativeOption option in WesterosiSharedPathOptions.YouthOptions)
            yield return option;

        yield return new NarrativeOption("crownlander_youth_gutters_option", new TextObject("{=bab_crownlander_youth_gutters_title}survived the gutters and alleys of King's Landing."), new TextObject("{=bab_crownlander_youth_gutters_desc}After disaster took your family or drove you from home, you slept in doorways, ran errands, dodged gold cloaks, and survived until a kind hand or hard necessity pulled you from the gutters."), (args, u) => u.UpgradeAthleticsRoguerySkills(args, DefaultCharacterAttributes.Cunning), ccm => IsCrownlander(ccm) && ccm.CharacterCreationContent.SelectedParentOccupation != CharacterOccupations.Retainer && (NarrativeChoiceState.ChildhoodWas("childhood_detail_option", "childhood_brawn_option") || NarrativeChoiceState.EducationWas("education_merchant_market_option", "education_artisan_guild_option", "education_farmer_market_option")), ccm => SelectYouth(ccm, "bandit", "act_childhood_clever"));

        yield return new NarrativeOption("crownlander_youth_squire_option", new TextObject("{=bab_crownlander_youth_squire_title}served a knight as page and squire."), new TextObject("{=bab_crownlander_youth_squire_desc}Through your family's service you entered the royal court and the castles along the Blackwater, carrying messages, tending horses and harness, and training beneath an experienced knight."), (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsCrownlander(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer || NarrativeChoiceState.ChildhoodWas("childhood_horse_option", "crownlander_childhood_court_rumours_option") || NarrativeChoiceState.EducationWas("crownlander_education_court_page_option"))), ccm => SelectYouth(ccm, "noble", "act_childhood_apprentice"));
        yield return new NarrativeOption("crownlander_youth_levy_option", new TextObject("{=bab_crownlander_youth_levy_title}trained with the local levy."), new TextObject("{=bab_crownlander_youth_levy_desc}You drilled with the spears, shields, and bows used by the smallfolk of the Crownlands, learning to hold formation when fear and noise broke less disciplined ranks."), (args, u) => u.UpgradePolearmOneHandedSkills(args, DefaultCharacterAttributes.Vigor), ccm => IsCrownlander(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban || NarrativeChoiceState.ChildhoodWas("childhood_brawn_option"))), ccm => SelectYouth(ccm, "infantry", "act_childhood_fierce"));
        yield return new NarrativeOption("crownlander_youth_scout_option", new TextObject("{=bab_crownlander_youth_scout_title}ranged ahead of travellers and hunting parties."), new TextObject("{=bab_crownlander_youth_scout_desc}Your knowledge of busy roads, the kingswood, and the Blackwater made you useful as a guide and scout, watching for broken tracks, hostile riders, and safe ground ahead."), (args, u) => u.UpgradeScoutingBowSkills(args, DefaultCharacterAttributes.Cunning), ccm => IsCrownlander(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Hunter || NarrativeChoiceState.ChildhoodWas("childhood_detail_option", "crownlander_childhood_court_rumours_option")), ccm => SelectYouth(ccm, "skirmisher", "act_childhood_fox"));
        yield return new NarrativeOption("crownlander_youth_courtier_option", new TextObject("{=bab_crownlander_youth_courtier_title}learned to survive the intrigues of a noble court."), new TextObject("{=bab_crownlander_youth_courtier_desc}You remained among the royal court and the castles along the Blackwater, mastering household accounts, correspondence, courtesy, and the alliances hidden beneath feasts and ceremonies."), (args, u) => u.UpgradeStewardCharmSkills(args, DefaultCharacterAttributes.Social), ccm => IsCrownlander(ccm) && (CharacterObject.PlayerCharacter.IsFemale && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer || NarrativeChoiceState.EducationWas("education_retainer_lady_option", "crownlander_education_court_lady_option"))), ccm => SelectYouth(ccm, "noble", "act_childhood_manners"));
        yield return new NarrativeOption("crownlander_youth_factor_option", new TextObject("{=bab_crownlander_youth_factor_title}acted as a young factor for your family."), new TextObject("{=bab_crownlander_youth_factor_desc}You travelled through King's Landing's markets and river quays, inspecting goods, keeping accounts, and bargaining with people who respected profit more than birth."), (args, u) => u.UpgradeTradeCharmSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsCrownlander(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.MerchantUrban || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer), ccm => SelectYouth(ccm, "merchant", "act_childhood_book"));
        yield return new NarrativeOption("crownlander_youth_rebellious_option", new TextObject("{=bab_crownlander_youth_rebellious_title}trained secretly with horse and arms."), new TextObject("{=bab_crownlander_youth_rebellious_desc}The customs of the Crownlands did not expect you to become a warrior. You borrowed time, weapons, and instruction wherever you could, refusing to let that judgment decide your life."), (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsCrownlander(ccm) && (CharacterObject.PlayerCharacter.IsFemale && (NarrativeChoiceState.ChildhoodWas("childhood_brawn_option", "childhood_horse_option", "crownlander_childhood_court_rumours_option") || NarrativeChoiceState.EducationWas("education_retainer_stables_option"))), ccm => SelectYouth(ccm, "cavalry", "act_childhood_fierce"));
    }

    public IEnumerable<NarrativeOption> GetAdulthoodOptions()
    {
        foreach (NarrativeOption option in WesterosiSharedPathOptions.AdulthoodOptions)
            yield return option;

        yield return new NarrativeOption("crownlander_adulthood_city_house_option", new TextObject("{=bab_crownlander_adulthood_city_house_title}you rose to own a bathhouse, gaming den, or discreet house."), new TextObject("{=bab_crownlander_adulthood_city_house_desc}From servant or shop-girl you rose to keep a prosperous city house where merchants and gold cloaks spent freely and spoke carelessly. You protected those in your charge and learned the value of every confidence."), (args, u) => { u.UpgradeTradeCharmSkills(args, DefaultCharacterAttributes.Social); args.SetRenownToAdd(10); }, ccm => IsCrownlander(ccm) && CharacterObject.PlayerCharacter.IsFemale && NarrativeChoiceState.YouthWas("crownlander_youth_gutters_option", "westerosi_youth_noble_servant_option", "crownlander_youth_factor_option", "westerosi_youth_family_workshop_option"), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_manners"));

        yield return new NarrativeOption("crownlander_adulthood_tourney_knight_option", new TextObject("{=bab_crownlander_adulthood_tourney_knight_title}you travelled the tourney circuit as a knight."), new TextObject("{=bab_crownlander_adulthood_tourney_knight_desc}With horse, armour, and hard-won skill, you rode from one tourney in Westeros to the next, testing yourself in melees and lists while seeking ransom, patronage, and renown."), (args, u) => { u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance); args.SetRenownToAdd(20); }, ccm => IsCrownlander(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && NarrativeChoiceState.YouthWas("crownlander_youth_squire_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_apprentice"));
        yield return new NarrativeOption("crownlander_adulthood_mystery_knight_option", new TextObject("{=bab_crownlander_adulthood_mystery_knight_title}you entered the lists as a mystery knight."), new TextObject("{=bab_crownlander_adulthood_mystery_knight_desc}Hidden behind an unknown device and a closed helm, you defied custom and entered the lists. Whatever the heralds guessed, your courage and skill could not be dismissed."), (args, u) => { u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance); args.SetRenownToAdd(20); }, ccm => IsCrownlander(ccm) && (CharacterObject.PlayerCharacter.IsFemale && NarrativeChoiceState.YouthWas("crownlander_youth_rebellious_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_fierce"));
        yield return new NarrativeOption("crownlander_adulthood_campaign_option", new TextObject("{=bab_crownlander_adulthood_campaign_title}you distinguished yourself during a local campaign."), new TextObject("{=bab_crownlander_adulthood_campaign_desc}When banners were called in the Crownlands, you marched with the host and kept your courage when scouting, skirmishing, and hard close fighting replaced youthful drills."), (args, u) => { u.UpgradeLeadershipTacticsSkills(args, DefaultCharacterAttributes.Cunning); args.SetRenownToAdd(15); }, ccm => IsCrownlander(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && NarrativeChoiceState.YouthWas("crownlander_youth_levy_option", "crownlander_youth_scout_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_drafted_to_war_pose"));
        yield return new NarrativeOption("crownlander_adulthood_court_service_option", new TextObject("{=bab_crownlander_adulthood_court_service_title}you won influence in a great household."), new TextObject("{=bab_crownlander_adulthood_court_service_desc}Your judgment, discretion, and command of household politics earned you trust in the royal court and the castles along the Blackwater, and people began seeking your help before presenting delicate requests."), (args, u) => { u.UpgradeStewardCharmSkills(args, DefaultCharacterAttributes.Social); args.SetRenownToAdd(10); }, ccm => IsCrownlander(ccm) && (NarrativeChoiceState.YouthWas("crownlander_youth_courtier_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_manners"));
        yield return new NarrativeOption("crownlander_adulthood_trade_venture_option", new TextObject("{=bab_crownlander_adulthood_trade_venture_title}you completed a profitable trading venture."), new TextObject("{=bab_crownlander_adulthood_trade_venture_desc}You organized credit, guards, transport, and buyers for a venture through King's Landing's markets and river quays, returning with both profit and a reputation for sound judgment."), (args, u) => { u.UpgradeTradeLeadershipSkills(args, DefaultCharacterAttributes.Intelligence); args.SetRenownToAdd(10); }, ccm => IsCrownlander(ccm) && (NarrativeChoiceState.YouthWas("crownlander_youth_factor_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_decisive"));
        yield return new NarrativeOption("crownlander_adulthood_border_deed_option", new TextObject("{=bab_crownlander_adulthood_border_deed_title}you protected travellers from outlaws."), new TextObject("{=bab_crownlander_adulthood_border_deed_desc}Your knowledge of busy roads, the kingswood, and the Blackwater let you find an outlaw band that had preyed upon local travellers. You guided armed men to its camp and helped break it."), (args, u) => { u.UpgradeScoutingTacticsSkills(args, DefaultCharacterAttributes.Cunning); args.SetRenownToAdd(10); }, ccm => IsCrownlander(ccm) && (NarrativeChoiceState.YouthWas("crownlander_youth_scout_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_tough"));
    }

    private static bool IsCrownlander(CharacterCreationManager ccm) => ccm.CharacterCreationContent.SelectedCulture.StringId == "crownlander";
    private static NarrativeOption CreateParentOption(string id, string titleText, string descriptionText, System.Action<NarrativeMenuOptionArgs, NarrativeSkillUpgrades> setArgs, string occupationType, string motherAnimation, string fatherAnimation)
    {
        return new NarrativeOption(id, new TextObject(titleText), new TextObject(descriptionText), setArgs, IsCrownlander, ccm =>
        {
            ccm.CharacterCreationContent.SetParentOccupation(occupationType);
            string cultureId = ccm.CharacterCreationContent.SelectedCulture.StringId;
            string motherEquipmentId = NarrativeEquipmentHelper.GetMotherEquipmentId(ccm, occupationType, cultureId);
            string fatherEquipmentId = NarrativeEquipmentHelper.GetFatherEquipmentId(ccm, occupationType, cultureId);
            NarrativeEquipmentHelper.SetParentEquipment(ccm, motherEquipmentId, fatherEquipmentId, motherAnimation, fatherAnimation);
        });
    }

    private void SelectYouth(CharacterCreationManager ccm, string titleType, string animation)
    {
        ccm.CharacterCreationContent.SelectedTitleType = titleType;
        string playerEquipmentId = NarrativeEquipmentHelper.GetPlayerEquipmentId(ccm, titleType, CultureId, Hero.MainHero.IsFemale);
        NarrativeEquipmentHelper.SetPlayerEquipment(ccm, playerEquipmentId, animation);
    }
}
