using System.Collections.Generic;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.CharacterCreationContent;
using TaleWorlds.Core;
using TaleWorlds.Localization;

namespace BloodAndBittersteel.Features.CharacterCreation.Cultures;

public class DornishCulture : ICharacterCreationCulture
{
    public string CultureId => "dornish";

    public IEnumerable<NarrativeOption> GetParentOptions()
    {
        yield return CreateParentOption("dornish_retainer_option", "{=bab_crownlander_parent_retainer_title}A lord's retainers", "{=bab_dornish_parent_retainer_desc}Your family served a Dornish lord, administering his holdings and keeping riders ready to defend well, pass, and holdfast.", (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Social), CharacterOccupations.Retainer, "act_character_creation_female_default_side_to_side_1", "act_character_creation_male_default_side_to_side_1");
        yield return CreateParentOption("dornish_merchant_option", "{=651FhzdR}Urban merchants", "{=bab_dornish_parent_merchant_desc}Your family traded wine, fruit, spices, and cloth along Dorne's roads and through its ports.", (args, u) => u.UpgradeTradeCharmSkills(args, DefaultCharacterAttributes.Intelligence), CharacterOccupations.MerchantUrban, "act_character_creation_female_default_mother_front", "act_character_creation_male_default_mother_front");
        yield return CreateParentOption("dornish_farmer_option", "{=RDfXuVxT}Yeomen", "{=bab_dornish_parent_farmer_desc}Your family tended irrigated fields and orchards, guarding every drop of water and answering the local lord's summons.", (args, u) => u.UpgradePolearmCrossbowSkills(args, DefaultCharacterAttributes.Endurance), CharacterOccupations.Farmer, "act_character_creation_female_default_father_sitting", "act_character_creation_male_default_father_sitting");
        yield return CreateParentOption("dornish_blacksmith_option", "{=p2KIhGbE}Urban blacksmith", "{=bab_dornish_parent_blacksmith_desc}Your family ran a smithy in a Dornish town, making tools for field and vineyard as well as arms for guards and riders.", (args, u) => u.UpgradeCraftingTwoHandedSkills(args, DefaultCharacterAttributes.Vigor), CharacterOccupations.ArtisanUrban, "act_character_creation_female_default_side_to_side_2", "act_character_creation_male_default_side_to_side_2");
        yield return CreateParentOption("dornish_hunter_option", "{=YcnK0Thk}Hunters", "{=bab_dornish_parent_hunter_desc}Your family hunted the stony hills and dry valleys, reading faint tracks and surviving far from any well.", (args, u) => u.UpgradeScoutingCrossbowSkills(args, DefaultCharacterAttributes.Control), CharacterOccupations.Hunter, "act_character_creation_female_default_side_to_side_3", "act_character_creation_male_default_side_to_side_3");
    }

    public IEnumerable<NarrativeOption> GetChildhoodOptions()
    {
        foreach (NarrativeOption option in MainlandChildhoodOptions.Shared)
            yield return option;

        yield return new NarrativeOption("dornish_childhood_water_gardens_option", new TextObject("{=bab_dornish_childhood_water_gardens_title}played in the pools of the Water Gardens."), new TextObject("{=bab_dornish_childhood_water_gardens_desc}You were fostered among children of every station, swimming, racing, and playing shoulder-riding games beneath the fountains and orange trees."), (args, u) => u.UpgradeLeadershipCharmSkills(args, DefaultCharacterAttributes.Social), ccm => IsDornish(ccm), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_childhood_character", "act_childhood_athlete"));
        yield return new NarrativeOption("dornish_childhood_sand_steeds_option", new TextObject("{=bab_dornish_childhood_sand_steeds_title}learned to ride the sand steeds."), new TextObject("{=bab_dornish_childhood_sand_steeds_desc}You were trusted with the swift, enduring horses of Dorne and learned to ride lightly over dust, stone, and broken ground."), (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsDornish(ccm), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_childhood_character", "act_childhood_animals"));
        yield return new NarrativeOption("dornish_childhood_water_lesson_option", new TextObject("{=bab_dornish_childhood_water_lesson_title}learned the worth of every drop of water."), new TextObject("{=bab_dornish_childhood_water_lesson_desc}You helped inspect wells, cisterns, and channels, learning that water wisely shared could bind a community together while water stolen could begin a feud."), (args, u) => u.UpgradeStewardTacticsSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsDornish(ccm), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_childhood_character", "act_childhood_memory"));
    }

    public IEnumerable<NarrativeOption> GetEducationOptions()
    {
        foreach (NarrativeOption option in MainlandEducationOptions.Shared)
            yield return option;

        yield return new NarrativeOption("dornish_education_water_gardens_option", new TextObject("{=bab_dornish_education_water_gardens_title}were fostered with children of every station."), new TextObject("{=bab_dornish_education_water_gardens_desc}You spent part of your youth among other Dornish children under noble protection, learning that prince, merchant, craftsman, and peasant all depended upon the same land and water."), (args, u) => u.UpgradeLeadershipCharmSkills(args, DefaultCharacterAttributes.Social), ccm => IsDornish(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.MerchantUrban || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer), ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_manners", "", ""));
        yield return new NarrativeOption("dornish_education_dornish_heir_option", new TextObject("{=bab_dornish_education_dornish_heir_title}trained beside the household's heirs."), new TextObject("{=bab_dornish_education_dornish_heir_desc}Dornish custom placed fewer limits upon daughters, and you were taught beside the household's young heirs to ride, judge disputes, and defend the family's rights."), (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsDornish(ccm) && ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer && CharacterObject.PlayerCharacter.IsFemale, ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_apprentice", "", ""));
        yield return new NarrativeOption("dornish_education_water_steward_option", new TextObject("{=bab_dornish_education_water_steward_title}helped measure wells and watercourses."), new TextObject("{=bab_dornish_education_water_steward_desc}In Dorne, a neglected cistern or stolen flow of water could ruin a holding. You learned to inspect channels, ration stores, and settle quarrels over irrigation."), (args, u) => u.UpgradeStewardTacticsSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsDornish(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban), ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_grit", "", ""));
    }

    public IEnumerable<NarrativeOption> GetYouthOptions()
    {
        foreach (NarrativeOption option in WesterosiSharedPathOptions.YouthOptions)
            yield return option;

        yield return new NarrativeOption("dornish_youth_heir_training_option", new TextObject("{=bab_dornish_youth_heir_training_title}trained beside the household's heirs."), new TextObject("{=bab_dornish_youth_heir_training_desc}Dornish custom did not bar you for being a daughter. You studied riding, arms, judgment, and command beside those expected to inherit land and duty."), (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsDornish(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer || NarrativeChoiceState.EducationWas("dornish_education_dornish_heir_option")), ccm => SelectYouth(ccm, "noble", "act_childhood_apprentice"));
        yield return new NarrativeOption("dornish_youth_sand_rider_option", new TextObject("{=bab_dornish_youth_sand_rider_title}rode with the scouts of the desert and passes."), new TextObject("{=bab_dornish_youth_sand_rider_desc}You learned to spare your mount, find water, read distant dust, and strike quickly before a heavier enemy could close."), (args, u) => u.UpgradeScoutingRidingSkills(args, DefaultCharacterAttributes.Cunning), ccm => IsDornish(ccm) && (NarrativeChoiceState.ChildhoodWas("dornish_childhood_sand_steeds_option", "childhood_horse_option") || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Hunter), ccm => SelectYouth(ccm, "cavalry", "act_childhood_fox"));
        yield return new NarrativeOption("dornish_youth_spear_option", new TextObject("{=bab_dornish_youth_spear_title}trained with spear and shield."), new TextObject("{=bab_dornish_youth_spear_desc}You drilled to defend wells, passes, and holdfasts, where discipline and knowledge of the ground mattered more than heavy armour."), (args, u) => u.UpgradePolearmOneHandedSkills(args, DefaultCharacterAttributes.Vigor), ccm => IsDornish(ccm) && (NarrativeChoiceState.ChildhoodWas("childhood_brawn_option", "dornish_childhood_water_gardens_option") || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer), ccm => SelectYouth(ccm, "infantry", "act_childhood_fierce"));
        yield return new NarrativeOption("dornish_youth_court_envoy_option", new TextObject("{=bab_dornish_youth_court_envoy_title}carried messages between Dornish courts."), new TextObject("{=bab_dornish_youth_court_envoy_desc}You learned the courtesies of prince, landed knight, merchant, and orphan alike while carrying private words between households."), (args, u) => u.UpgradeLeadershipCharmSkills(args, DefaultCharacterAttributes.Social), ccm => IsDornish(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.MerchantUrban || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban || NarrativeChoiceState.EducationWas("dornish_education_water_gardens_option")), ccm => SelectYouth(ccm, "noble", "act_childhood_manners"));
        yield return new NarrativeOption("dornish_youth_water_steward_option", new TextObject("{=bab_dornish_youth_water_steward_title}helped govern wells and watercourses."), new TextObject("{=bab_dornish_youth_water_steward_desc}You settled small quarrels, organized repairs, and learned to measure need before pride turned a dispute over water into bloodshed."), (args, u) => u.UpgradeStewardTacticsSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsDornish(ccm) && (NarrativeChoiceState.ChildhoodWas("dornish_childhood_water_lesson_option") || NarrativeChoiceState.EducationWas("dornish_education_water_steward_option")), ccm => SelectYouth(ccm, "guard", "act_childhood_book"));
        yield return new NarrativeOption("dornish_youth_smuggler_option", new TextObject("{=bab_dornish_youth_smuggler_title}rode with smugglers and desert guides."), new TextObject("{=bab_dornish_youth_smuggler_desc}You learned hidden springs, lonely tracks, and the ways by which forbidden goods and hunted people crossed Dorne unseen."), (args, u) => u.UpgradeRogueryCharmSkills(args, DefaultCharacterAttributes.Cunning), ccm => IsDornish(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Hunter || NarrativeChoiceState.ChildhoodWas("childhood_detail_option")), ccm => SelectYouth(ccm, "bandit", "act_childhood_fox"));
    }

    public IEnumerable<NarrativeOption> GetAdulthoodOptions()
    {
        foreach (NarrativeOption option in WesterosiSharedPathOptions.AdulthoodOptions)
            yield return option;

        yield return new NarrativeOption("dornish_adulthood_perfume_trade_option", new TextObject("{=bab_dornish_adulthood_perfume_trade_title}you prospered in oils, spices, and perfumes."), new TextObject("{=bab_dornish_adulthood_perfume_trade_desc}You judged rare scents, guarded recipes, and negotiated with growers and sea traders until Dornish oils and perfumes carried your name beyond the passes."), (args, u) => { u.UpgradeTradeCharmSkills(args, DefaultCharacterAttributes.Intelligence); args.SetRenownToAdd(10); }, ccm => IsDornish(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.MerchantUrban || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban || NarrativeChoiceState.YouthWas("westerosi_youth_family_workshop_option", "dornish_youth_court_envoy_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_decisive"));

        yield return new NarrativeOption("dornish_adulthood_border_command_option", new TextObject("{=bab_dornish_adulthood_border_command_title}you led riders in a border clash."), new TextObject("{=bab_dornish_adulthood_border_command_desc}When raiders crossed a pass, you gathered riders, found their trail, and struck before they could escape with captives and livestock."), (args, u) => { u.UpgradeLeadershipTacticsSkills(args, DefaultCharacterAttributes.Cunning); args.SetRenownToAdd(20); }, ccm => IsDornish(ccm) && (NarrativeChoiceState.YouthWas("dornish_youth_heir_training_option", "dornish_youth_sand_rider_option", "dornish_youth_spear_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_drafted_to_war_pose"));
        yield return new NarrativeOption("dornish_adulthood_water_peace_option", new TextObject("{=bab_dornish_adulthood_water_peace_title}you ended a feud over water."), new TextObject("{=bab_dornish_adulthood_water_peace_desc}Two communities stood ready to shed blood over a failing channel. You found a fair division, organized repairs, and made both sides accept it."), (args, u) => { u.UpgradeStewardCharmSkills(args, DefaultCharacterAttributes.Social); args.SetRenownToAdd(15); }, ccm => IsDornish(ccm) && (NarrativeChoiceState.YouthWas("dornish_youth_water_steward_option", "dornish_youth_court_envoy_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_manners"));
        yield return new NarrativeOption("dornish_adulthood_desert_caravan_option", new TextObject("{=bab_dornish_adulthood_desert_caravan_title}you brought a caravan safely across Dorne."), new TextObject("{=bab_dornish_adulthood_desert_caravan_desc}Heat, distance, and uncertain wells threatened the journey, but your planning and knowledge delivered every wagon and traveller alive."), (args, u) => { u.UpgradeTradeLeadershipSkills(args, DefaultCharacterAttributes.Intelligence); args.SetRenownToAdd(10); }, ccm => IsDornish(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.MerchantUrban || NarrativeChoiceState.YouthWas("dornish_youth_sand_rider_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_decisive"));
        yield return new NarrativeOption("dornish_adulthood_court_mission_option", new TextObject("{=bab_dornish_adulthood_court_mission_title}you resolved a delicate mission between courts."), new TextObject("{=bab_dornish_adulthood_court_mission_desc}You carried words that could not be trusted to parchment and returned with an agreement neither household could have reached openly."), (args, u) => { u.UpgradeLeadershipCharmSkills(args, DefaultCharacterAttributes.Social); args.SetRenownToAdd(15); }, ccm => IsDornish(ccm) && (NarrativeChoiceState.YouthWas("dornish_youth_court_envoy_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_manners"));
        yield return new NarrativeOption("dornish_adulthood_outlaw_road_option", new TextObject("{=bab_dornish_adulthood_outlaw_road_title}you broke an outlaw ring along the desert roads."), new TextObject("{=bab_dornish_adulthood_outlaw_road_desc}You used hidden tracks against the smugglers and broken men who had taught them to you, freeing travellers and recovering stolen goods."), (args, u) => { u.UpgradeScoutingTacticsSkills(args, DefaultCharacterAttributes.Cunning); args.SetRenownToAdd(10); }, ccm => IsDornish(ccm) && (NarrativeChoiceState.YouthWas("dornish_youth_smuggler_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_tough"));
    }

    private static bool IsDornish(CharacterCreationManager ccm) => ccm.CharacterCreationContent.SelectedCulture.StringId == "dornish";

    private static NarrativeOption CreateParentOption(string id, string titleText, string descriptionText, System.Action<NarrativeMenuOptionArgs, NarrativeSkillUpgrades> setArgs, string occupationType, string motherAnimation, string fatherAnimation)
    {
        return new NarrativeOption(id, new TextObject(titleText), new TextObject(descriptionText), setArgs, IsDornish, ccm =>
        {
            ccm.CharacterCreationContent.SetParentOccupation(occupationType);
            string cultureId = ccm.CharacterCreationContent.SelectedCulture.StringId;
            string motherEquipmentId = NarrativeEquipmentHelper.GetMotherEquipmentId(ccm, occupationType, cultureId);
            string fatherEquipmentId = NarrativeEquipmentHelper.GetFatherEquipmentId(ccm, occupationType, cultureId);
            NarrativeEquipmentHelper.SetParentEquipment(ccm, motherEquipmentId, fatherEquipmentId, motherAnimation, fatherAnimation);
        });
    }

    private void SelectYouth(CharacterCreationManager ccm, string titleType, string animation)
    {
        ccm.CharacterCreationContent.SelectedTitleType = titleType;
        string playerEquipmentId = NarrativeEquipmentHelper.GetPlayerEquipmentId(ccm, titleType, CultureId, Hero.MainHero.IsFemale);
        NarrativeEquipmentHelper.SetPlayerEquipment(ccm, playerEquipmentId, animation);
    }
}
