using System.Collections.Generic;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.CharacterCreationContent;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.Core;
using TaleWorlds.Localization;

namespace BloodAndBittersteel.Features.CharacterCreation.Cultures;

public class IronIslanderCulture : ICharacterCreationCulture
{
    public string CultureId => "ironislander";

    public IEnumerable<NarrativeOption> GetParentOptions()
    {
        yield return CreateParentOption("ironislander_retainer_option", "{=bab_crownlander_parent_retainer_title}A lord's retainers", "{=bab_ironislander_parent_retainer_desc}Your family served an Ironborn lord or captain, overseeing his hall, ships, and fighting men when the banners were raised.", (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Social), CharacterOccupations.Retainer, "act_character_creation_female_default_side_to_side_1", "act_character_creation_male_default_side_to_side_1");
        yield return CreateParentOption("ironislander_merchant_option", "{=651FhzdR}Urban merchants", "{=bab_ironislander_parent_merchant_desc}Your family traded fish, iron, timber, and goods brought home by the longships of the Iron Islands.", (args, u) => u.UpgradeTradeCharmSkills(args, DefaultCharacterAttributes.Intelligence), CharacterOccupations.MerchantUrban, "act_character_creation_female_default_mother_front", "act_character_creation_male_default_mother_front");
        yield return CreateParentOption("ironislander_farmer_option", "{=RDfXuVxT}Yeomen", "{=bab_ironislander_parent_farmer_desc}Your family scratched a living from thin soil and cold shores, working land and sea under a local lord.", (args, u) => u.UpgradePolearmCrossbowSkills(args, DefaultCharacterAttributes.Endurance), CharacterOccupations.Farmer, "act_character_creation_female_default_father_sitting", "act_character_creation_male_default_father_sitting");
        yield return CreateParentOption("ironislander_blacksmith_option", "{=p2KIhGbE}Urban blacksmith", "{=bab_ironislander_parent_blacksmith_desc}Your family worked an island forge, shaping local iron into tools, axes, mail, and fittings for ships.", (args, u) => u.UpgradeCraftingTwoHandedSkills(args, DefaultCharacterAttributes.Vigor), CharacterOccupations.ArtisanUrban, "act_character_creation_female_default_side_to_side_2", "act_character_creation_male_default_side_to_side_2");
        yield return CreateParentOption("ironislander_hunter_option", "{=YcnK0Thk}Hunters", "{=bab_ironislander_parent_hunter_desc}Your family hunted seabirds and seals along the coasts and knew every cove, cliff path, and treacherous current nearby.", (args, u) => u.UpgradeScoutingCrossbowSkills(args, DefaultCharacterAttributes.Control), CharacterOccupations.Hunter, "act_character_creation_female_default_side_to_side_3", "act_character_creation_male_default_side_to_side_3");
    }

    public IEnumerable<NarrativeOption> GetChildhoodOptions()
    {
        foreach (NarrativeOption option in MainlandChildhoodOptions.Shared)
            yield return option;

        yield return new NarrativeOption("ironislander_childhood_finger_dance_option", new TextObject("{=bab_ironislander_childhood_finger_dance_title}played the finger dance."), new TextObject("{=bab_ironislander_childhood_finger_dance_desc}You joined older children in the dangerous game of tossing and catching a hand axe, learning quick feet, a steady eye, and little fear of blood."), (args, u) => u.UpgradeThrowingOneHandedSkills(args, DefaultCharacterAttributes.Control), ccm => IsIronIslander(ccm), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_childhood_character", "act_childhood_fox"));
        yield return new NarrativeOption("ironislander_childhood_oars_option", new TextObject("{=bab_ironislander_childhood_oars_title}learned the oar and sail."), new TextObject("{=bab_ironislander_childhood_oars_desc}You spent your childhood in fishing boats and longships, hauling rope, pulling an oar, reading wind, and finding balance on a rolling deck."), (args, u) => u.UpgradeAthleticsCraftingSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsIronIslander(ccm), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_childhood_character", "act_childhood_athlete"));
        yield return new NarrativeOption("ironislander_childhood_reavers_tales_option", new TextObject("{=bab_ironislander_childhood_reavers_tales_title}listened to the tales of captains and reavers."), new TextObject("{=bab_ironislander_childhood_reavers_tales_desc}At the hearth you memorized boast, feud, voyage, and raid, learning which captains won loyalty and which brought their crews only grief."), (args, u) => u.UpgradeLeadershipTacticsSkills(args, DefaultCharacterAttributes.Social), ccm => IsIronIslander(ccm), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_childhood_character", "act_childhood_memory"));
    }

    public IEnumerable<NarrativeOption> GetEducationOptions()
    {
        foreach (NarrativeOption option in MainlandEducationOptions.Shared)
            yield return option;

        yield return new NarrativeOption("ironislander_education_joined_crew_option", new TextObject("{=bab_ironislander_education_joined_crew_title}joined a longship's crew."), new TextObject("{=bab_ironislander_education_joined_crew_desc}At the age when other children entered apprenticeships, you went aboard a longship and learned the oar, sail, axe, and harsh discipline of a captain's crew."), (args, u) => u.UpgradeAthleticsOneHandedSkills(args, DefaultCharacterAttributes.Vigor), ccm => IsIronIslander(ccm) && ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer && !CharacterObject.PlayerCharacter.IsFemale, ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_athlete", "", ""));
        yield return new NarrativeOption("ironislander_education_captains_hall_option", new TextObject("{=bab_ironislander_education_captains_hall_title}helped govern a captain's hall."), new TextObject("{=bab_ironislander_education_captains_hall_desc}You learned to reckon stores, direct servants and thralls, receive petitioners, and keep a hard household functioning while its fighting men were away at sea."), (args, u) => u.UpgradeStewardTacticsSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsIronIslander(ccm) && ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer && CharacterObject.PlayerCharacter.IsFemale, ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_manners", "", ""));
        yield return new NarrativeOption("ironislander_education_shipwright_option", new TextObject("{=bab_ironislander_education_shipwright_title}worked beside shipwrights and sailmakers."), new TextObject("{=bab_ironislander_education_shipwright_desc}You carried timber, pitch, rope, and cloth while learning how island craftsmen built and supplied the longships upon which every captain's fortune depended."), (args, u) => u.UpgradeTradeCraftingSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsIronIslander(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.MerchantUrban || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban), ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_grit", "", ""));
        yield return new NarrativeOption("ironislander_education_nets_halls_option", new TextObject("{=bab_ironislander_education_nets_halls_title}tended nets and salt-stained halls."), new TextObject("{=bab_ironislander_education_nets_halls_desc}While the men were away at sea, you mended nets, smoked fish, counted stores, and helped keep a hard island household alive until the sails returned."), (args, u) => u.UpgradeLeadershipStewardSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsIronIslander(ccm) && CharacterObject.PlayerCharacter.IsFemale && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Hunter || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer), ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_grit", "", ""));
    }

    public IEnumerable<NarrativeOption> GetYouthOptions()
    {
        foreach (NarrativeOption option in WesterosiSharedPathOptions.YouthOptions)
            yield return option;

        yield return new NarrativeOption("ironislander_youth_crew_option", new TextObject("{=bab_ironislander_youth_crew_title}earned a place in a longship's crew."), new TextObject("{=bab_ironislander_youth_crew_desc}You proved that you could pull an oar, handle sail, obey a shouted order, and stand fast when the deck became a killing ground."), (args, u) => u.UpgradeAthleticsOneHandedSkills(args, DefaultCharacterAttributes.Vigor), ccm => IsIronIslander(ccm) && (NarrativeChoiceState.ChildhoodWas("ironislander_childhood_oars_option", "ironislander_childhood_finger_dance_option") || NarrativeChoiceState.EducationWas("ironislander_education_joined_crew_option") || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Hunter), ccm => SelectYouth(ccm, "infantry", "act_childhood_athlete"));
        yield return new NarrativeOption("ironislander_youth_axe_option", new TextObject("{=bab_ironislander_youth_axe_title}became deadly in the finger dance and axe drill."), new TextObject("{=bab_ironislander_youth_axe_desc}Games became training, and training became reputation as you learned to throw, catch, and fight with the axes favoured aboard ship."), (args, u) => u.UpgradeThrowingOneHandedSkills(args, DefaultCharacterAttributes.Control), ccm => IsIronIslander(ccm) && (NarrativeChoiceState.ChildhoodWas("ironislander_childhood_finger_dance_option", "childhood_brawn_option")), ccm => SelectYouth(ccm, "skirmisher", "act_childhood_fierce"));
        yield return new NarrativeOption("ironislander_youth_navigator_option", new TextObject("{=bab_ironislander_youth_navigator_title}learned currents, stars, and sea roads."), new TextObject("{=bab_ironislander_youth_navigator_desc}You sailed with traders and captains who taught you to reckon stores, judge weather, and bring a vessel home when land had vanished behind the horizon."), (args, u) => u.UpgradeTradeTacticsSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsIronIslander(ccm) && (NarrativeChoiceState.ChildhoodWas("ironislander_childhood_oars_option", "childhood_smart_option") || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.MerchantUrban), ccm => SelectYouth(ccm, "merchant", "act_childhood_book"));
        yield return new NarrativeOption("ironislander_youth_captains_daughter_option", new TextObject("{=bab_ironislander_youth_captains_daughter_title}claimed a warrior's place among the crew."), new TextObject("{=bab_ironislander_youth_captains_daughter_desc}Some men mocked a woman who wanted axe and command. You answered with skill, nerve, and the loyalty of shipmates willing to follow you."), (args, u) => u.UpgradeLeadershipTacticsSkills(args, DefaultCharacterAttributes.Social), ccm => IsIronIslander(ccm) && (CharacterObject.PlayerCharacter.IsFemale && (NarrativeChoiceState.ChildhoodWas("ironislander_childhood_finger_dance_option", "ironislander_childhood_oars_option", "childhood_brawn_option") || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer)), ccm => SelectYouth(ccm, "cavalry", "act_childhood_fierce"));
        yield return new NarrativeOption("ironislander_youth_hall_keeper_option", new TextObject("{=bab_ironislander_youth_hall_keeper_title}managed a captain's hall and stores."), new TextObject("{=bab_ironislander_youth_hall_keeper_desc}You directed thralls and servants, accounted for food and plunder, heard petitions, and kept the household strong while ships were away."), (args, u) => u.UpgradeLeadershipStewardSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsIronIslander(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer || NarrativeChoiceState.EducationWas("ironislander_education_captains_hall_option")), ccm => SelectYouth(ccm, "noble", "act_childhood_manners"));
        yield return new NarrativeOption("ironislander_youth_shipwright_option", new TextObject("{=bab_ironislander_youth_shipwright_title}apprenticed with shipwrights and sailmakers."), new TextObject("{=bab_ironislander_youth_shipwright_desc}You learned the timber, iron, rope, pitch, and cloth that turned island labour into a swift longship."), (args, u) => u.UpgradeTradeCraftingSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsIronIslander(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban || NarrativeChoiceState.EducationWas("ironislander_education_shipwright_option")), ccm => SelectYouth(ccm, "guard", "act_childhood_grit"));
    }

    public IEnumerable<NarrativeOption> GetAdulthoodOptions()
    {
        foreach (NarrativeOption option in WesterosiSharedPathOptions.AdulthoodOptions)
            yield return option;

        yield return new NarrativeOption("ironislander_adulthood_iron_price_option", new TextObject("{=bab_ironislander_adulthood_iron_price_title}you paid the iron price on your first reaving."), new TextObject("{=bab_ironislander_adulthood_iron_price_desc}You went ashore beneath hostile walls and returned to the ships with plunder won by courage rather than coin."), (args, u) => { u.UpgradeLeadershipTacticsSkills(args, DefaultCharacterAttributes.Vigor); args.SetRenownToAdd(20); }, ccm => IsIronIslander(ccm) && (NarrativeChoiceState.YouthWas("ironislander_youth_crew_option", "ironislander_youth_axe_option", "ironislander_youth_captains_daughter_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_drafted_to_war_pose"));
        yield return new NarrativeOption("ironislander_adulthood_crew_command_option", new TextObject("{=bab_ironislander_adulthood_crew_command_title}you won command of a crew."), new TextObject("{=bab_ironislander_adulthood_crew_command_desc}When confusion and fear seized the deck, your orders saved the ship. Afterward, seasoned hands accepted your right to command them."), (args, u) => { u.UpgradeLeadershipTacticsSkills(args, DefaultCharacterAttributes.Social); args.SetRenownToAdd(20); }, ccm => IsIronIslander(ccm) && (NarrativeChoiceState.YouthWas("ironislander_youth_crew_option", "ironislander_youth_captains_daughter_option", "ironislander_youth_navigator_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_decisive"));
        yield return new NarrativeOption("ironislander_adulthood_sea_venture_option", new TextObject("{=bab_ironislander_adulthood_sea_venture_title}you returned rich from a distant voyage."), new TextObject("{=bab_ironislander_adulthood_sea_venture_desc}You chose cargo, ports, and season wisely, surviving storm and piracy to return with profit and hard knowledge of foreign shores."), (args, u) => { u.UpgradeTradeLeadershipSkills(args, DefaultCharacterAttributes.Intelligence); args.SetRenownToAdd(10); }, ccm => IsIronIslander(ccm) && (NarrativeChoiceState.YouthWas("ironislander_youth_navigator_option", "ironislander_youth_shipwright_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_decisive"));
        yield return new NarrativeOption("ironislander_adulthood_hall_rule_option", new TextObject("{=bab_ironislander_adulthood_hall_rule_title}you kept a great hall together through a hard absence."), new TextObject("{=bab_ironislander_adulthood_hall_rule_desc}With the fighting men at sea, you rationed stores, settled quarrels, and kept dependants loyal until the ships returned."), (args, u) => { u.UpgradeLeadershipStewardSkills(args, DefaultCharacterAttributes.Social); args.SetRenownToAdd(15); }, ccm => IsIronIslander(ccm) && (NarrativeChoiceState.YouthWas("ironislander_youth_hall_keeper_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_manners"));
        yield return new NarrativeOption("ironislander_adulthood_coast_defence_option", new TextObject("{=bab_ironislander_adulthood_coast_defence_title}you drove raiders from an island shore."), new TextObject("{=bab_ironislander_adulthood_coast_defence_desc}You spotted hostile sails, mustered the shore folk, and struck the landing party before it could burn boats and carry off captives."), (args, u) => { u.UpgradeScoutingTacticsSkills(args, DefaultCharacterAttributes.Cunning); args.SetRenownToAdd(15); }, ccm => IsIronIslander(ccm) && (NarrativeChoiceState.YouthWas("ironislander_youth_axe_option", "ironislander_youth_crew_option", "ironislander_youth_captains_daughter_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_tough"));
        yield return new NarrativeOption("ironislander_adulthood_salt_fish_option", new TextObject("{=bab_ironislander_adulthood_salt_fish_title}you captained a fishing longship and worked the shore trade."), new TextObject("{=bab_ironislander_adulthood_salt_fish_desc}You organized boats and nets at sea, then smokehouses, curing sheds, and salt pans ashore, helping feed the isles while the reaving ships were away."), (args, u) => { u.UpgradeTradeLeadershipSkills(args, DefaultCharacterAttributes.Intelligence); args.SetRenownToAdd(5); }, ccm => IsIronIslander(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Hunter || NarrativeChoiceState.EducationWas("ironislander_education_nets_halls_option") || NarrativeChoiceState.YouthWas("westerosi_youth_family_farm_option", "ironislander_youth_navigator_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_grit"));
    }

    private static bool IsIronIslander(CharacterCreationManager ccm) => ccm.CharacterCreationContent.SelectedCulture.StringId == "ironislander";

    private static NarrativeOption CreateParentOption(string id, string titleText, string descriptionText, System.Action<NarrativeMenuOptionArgs, NarrativeSkillUpgrades> setArgs, string occupationType, string motherAnimation, string fatherAnimation)
    {
        return new NarrativeOption(id, new TextObject(titleText), new TextObject(descriptionText), setArgs, IsIronIslander, ccm =>
        {
            ccm.CharacterCreationContent.SetParentOccupation(occupationType);
            string cultureId = ccm.CharacterCreationContent.SelectedCulture.StringId;
            string motherEquipmentId = NarrativeEquipmentHelper.GetMotherEquipmentId(ccm, occupationType, cultureId);
            string fatherEquipmentId = NarrativeEquipmentHelper.GetFatherEquipmentId(ccm, occupationType, cultureId);
            NarrativeEquipmentHelper.SetParentEquipment(ccm, motherEquipmentId, fatherEquipmentId, motherAnimation, fatherAnimation);
        });
    }

    private void SelectYouth(CharacterCreationManager ccm, string titleType, string animation)
    {
        ccm.CharacterCreationContent.SelectedTitleType = titleType;
        string playerEquipmentId = NarrativeEquipmentHelper.GetPlayerEquipmentId(ccm, titleType, CultureId, Hero.MainHero.IsFemale);
        NarrativeEquipmentHelper.SetPlayerEquipment(ccm, playerEquipmentId, animation);
    }
}
