using System.Collections.Generic;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.CharacterCreationContent;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.Core;
using TaleWorlds.Localization;

namespace BloodAndBittersteel.Features.CharacterCreation.Cultures;

public class NorthmanCulture : ICharacterCreationCulture
{
    public string CultureId => "northman";

    public IEnumerable<NarrativeOption> GetParentOptions()
    {
        yield return CreateParentOption("northman_retainer_option", "{=bab_crownlander_parent_retainer_title}A lord's retainers", "{=bab_northman_parent_retainer_desc}Your family served a northern lord, keeping his hall and lands through long winters and mustering his folk when called.", (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Social), CharacterOccupations.Retainer, "act_character_creation_female_default_side_to_side_1", "act_character_creation_male_default_side_to_side_1");
        yield return CreateParentOption("northman_merchant_option", "{=651FhzdR}Urban merchants", "{=bab_northman_parent_merchant_desc}Your family traded wool, timber, hides, and preserved food between scattered northern holds and market towns.", (args, u) => u.UpgradeTradeCharmSkills(args, DefaultCharacterAttributes.Intelligence), CharacterOccupations.MerchantUrban, "act_character_creation_female_default_mother_front", "act_character_creation_male_default_mother_front");
        yield return CreateParentOption("northman_farmer_option", "{=RDfXuVxT}Yeomen", "{=bab_northman_parent_farmer_desc}Your family worked a northern holding, storing what the short summers yielded and serving in the levy when required.", (args, u) => u.UpgradePolearmCrossbowSkills(args, DefaultCharacterAttributes.Endurance), CharacterOccupations.Farmer, "act_character_creation_female_default_father_sitting", "act_character_creation_male_default_father_sitting");
        yield return CreateParentOption("northman_blacksmith_option", "{=p2KIhGbE}Urban blacksmith", "{=bab_northman_parent_blacksmith_desc}Your family kept a forge whose tools, nails, weapons, and horseshoes were essential to an isolated northern community.", (args, u) => u.UpgradeCraftingTwoHandedSkills(args, DefaultCharacterAttributes.Vigor), CharacterOccupations.ArtisanUrban, "act_character_creation_female_default_side_to_side_2", "act_character_creation_male_default_side_to_side_2");
        yield return CreateParentOption("northman_hunter_option", "{=YcnK0Thk}Hunters", "{=bab_northman_parent_hunter_desc}Your family ranged through deep forests and snowy hills, trapping fur and bringing down game through the lean months.", (args, u) => u.UpgradeScoutingCrossbowSkills(args, DefaultCharacterAttributes.Control), CharacterOccupations.Hunter, "act_character_creation_female_default_side_to_side_3", "act_character_creation_male_default_side_to_side_3");
    }

    public IEnumerable<NarrativeOption> GetChildhoodOptions()
    {
        foreach (NarrativeOption option in MainlandChildhoodOptions.Shared)
            yield return option;

        yield return new NarrativeOption("northman_childhood_winter_games_option", new TextObject("{=bab_northman_childhood_winter_games_title}made games of the winter work."), new TextObject("{=bab_northman_childhood_winter_games_desc}You raced to stack firewood, carry feed, clear snow, and check traps before the cold drove everyone back to the hall."), (args, u) => u.UpgradeAthleticsCraftingSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsNorthman(ccm), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_childhood_character", "act_childhood_grit"));
        yield return new NarrativeOption("northman_childhood_godswood_option", new TextObject("{=bab_northman_childhood_godswood_title}listened to old tales in the godswood."), new TextObject("{=bab_northman_childhood_godswood_desc}Beneath the heart tree you heard the histories of the First Men, old oaths, guest right, and the duties binding a lord to the people of the North."), (args, u) => u.UpgradeLeadershipCharmSkills(args, DefaultCharacterAttributes.Social), ccm => IsNorthman(ccm), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_childhood_character", "act_childhood_memory"));
        yield return new NarrativeOption("northman_childhood_raid_alarm_option", new TextObject("{=bab_northman_childhood_raid_alarm_title}learned what to do when the raid horn sounded."), new TextObject("{=bab_northman_childhood_raid_alarm_desc}Whether the danger came from sea, mountain, or forest, you learned to gather children and stores, carry warnings, and place a weapon in every capable hand."), (args, u) => u.UpgradeScoutingTacticsSkills(args, DefaultCharacterAttributes.Cunning), ccm => IsNorthman(ccm), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_childhood_character", "act_childhood_tough"));
    }

    public IEnumerable<NarrativeOption> GetEducationOptions()
    {
        foreach (NarrativeOption option in MainlandEducationOptions.Shared)
            yield return option;

        yield return new NarrativeOption("northman_education_northern_ward_option", new TextObject("{=bab_northman_education_northern_ward_title}were fostered in another northern hall."), new TextObject("{=bab_northman_education_northern_ward_desc}You were sent to another lord's hall as a ward, sharing lessons, meals, work, and training with the household's children until ties of duty became personal loyalty."), (args, u) => u.UpgradeLeadershipTacticsSkills(args, DefaultCharacterAttributes.Social), ccm => IsNorthman(ccm) && ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer, ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_manners", "", ""));
        yield return new NarrativeOption("northman_education_winter_stores_option", new TextObject("{=bab_northman_education_winter_stores_title}prepared the holding for winter."), new TextObject("{=bab_northman_education_winter_stores_desc}You counted grain, smoked meat, dried vegetables, cut peat, and inspected roofs and cellars, learning that poor stewardship could kill more surely than any sword."), (args, u) => u.UpgradeLeadershipStewardSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsNorthman(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.MerchantUrban), ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_grit", "", ""));
        yield return new NarrativeOption("northman_education_deep_woods_option", new TextObject("{=bab_northman_education_deep_woods_title}learned the deep northern woods."), new TextObject("{=bab_northman_education_deep_woods_desc}You travelled through pine forest, bog, and snow, learning to follow game, read weather, find shelter, and return safely when familiar paths disappeared."), (args, u) => u.UpgradeScoutingBowSkills(args, DefaultCharacterAttributes.Cunning), ccm => IsNorthman(ccm) && ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Hunter, ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_sharp", "", ""));
    }

    public IEnumerable<NarrativeOption> GetYouthOptions()
    {
        foreach (NarrativeOption option in WesterosiSharedPathOptions.YouthOptions)
            yield return option;

        yield return new NarrativeOption("northman_youth_hall_retainer_option", new TextObject("{=bab_northman_youth_hall_retainer_title}trained among a northern lord's household."), new TextObject("{=bab_northman_youth_hall_retainer_desc}You served in hall, stable, and yard, learning the direct loyalties and hard discipline expected of a northern retainer."), (args, u) => u.UpgradeLeadershipTacticsSkills(args, DefaultCharacterAttributes.Social), ccm => IsNorthman(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer || NarrativeChoiceState.EducationWas("northman_education_northern_ward_option"))), ccm => SelectYouth(ccm, "noble", "act_childhood_fierce"));
        yield return new NarrativeOption("northman_youth_levy_option", new TextObject("{=bab_northman_youth_levy_title}trained with the northern levy."), new TextObject("{=bab_northman_youth_levy_desc}You learned to march in cold rain, hold shield and spear, and keep formation beside neighbours who would remember whether you stood or ran."), (args, u) => u.UpgradePolearmOneHandedSkills(args, DefaultCharacterAttributes.Vigor), ccm => IsNorthman(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer || NarrativeChoiceState.ChildhoodWas("childhood_brawn_option", "northman_childhood_raid_alarm_option"))), ccm => SelectYouth(ccm, "infantry", "act_childhood_fierce"));
        yield return new NarrativeOption("northman_youth_woodsman_option", new TextObject("{=bab_northman_youth_woodsman_title}ranged through the deep northern woods."), new TextObject("{=bab_northman_youth_woodsman_desc}You learned to hunt, find shelter, read snow and weather, and guide others through country that swallowed careless travellers."), (args, u) => u.UpgradeScoutingBowSkills(args, DefaultCharacterAttributes.Cunning), ccm => IsNorthman(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Hunter || NarrativeChoiceState.ChildhoodWas("childhood_detail_option", "northman_childhood_winter_games_option")), ccm => SelectYouth(ccm, "skirmisher", "act_childhood_sharp"));
        yield return new NarrativeOption("northman_youth_winter_steward_option", new TextObject("{=bab_northman_youth_winter_steward_title}helped prepare a holding for winter."), new TextObject("{=bab_northman_youth_winter_steward_desc}You counted grain, fuel, fodder, preserved food, and warm beds, learning that a careless steward could doom a hall before spring."), (args, u) => u.UpgradeLeadershipStewardSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsNorthman(ccm) && (NarrativeChoiceState.ChildhoodWas("northman_childhood_winter_games_option", "childhood_smart_option") || NarrativeChoiceState.EducationWas("northman_education_winter_stores_option") || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban), ccm => SelectYouth(ccm, "guard", "act_childhood_book"));
        yield return new NarrativeOption("northman_youth_shieldwoman_option", new TextObject("{=bab_northman_youth_shieldwoman_title}claimed a place among the fighting women of the North."), new TextObject("{=bab_northman_youth_shieldwoman_desc}Like the women of shores long threatened by raiders, you refused to wait helplessly behind timber walls and trained to meet an attack with shield and steel."), (args, u) => u.UpgradeOneHandedTwoHandedSkills(args, DefaultCharacterAttributes.Vigor), ccm => IsNorthman(ccm) && (CharacterObject.PlayerCharacter.IsFemale && NarrativeChoiceState.ChildhoodWas("northman_childhood_raid_alarm_option", "childhood_brawn_option")), ccm => SelectYouth(ccm, "cavalry", "act_childhood_fierce"));
        yield return new NarrativeOption("northman_youth_wanderer_option", new TextObject("{=bab_northman_youth_wanderer_title}travelled with hunters and clan traders."), new TextObject("{=bab_northman_youth_wanderer_desc}You crossed long distances between lonely halls, learning the paths, customs, and grudges that maps and maesters rarely recorded."), (args, u) => u.UpgradeCharmScoutingSkills(args, DefaultCharacterAttributes.Cunning), ccm => IsNorthman(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Hunter || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.MerchantUrban || NarrativeChoiceState.ChildhoodWas("northman_childhood_godswood_option")), ccm => SelectYouth(ccm, "bandit", "act_childhood_fox"));
    }

    public IEnumerable<NarrativeOption> GetAdulthoodOptions()
    {
        foreach (NarrativeOption option in WesterosiSharedPathOptions.AdulthoodOptions)
            yield return option;

        yield return new NarrativeOption("northman_adulthood_raid_defence_option", new TextObject("{=bab_northman_adulthood_raid_defence_title}you led the defence against a raid."), new TextObject("{=bab_northman_adulthood_raid_defence_desc}You carried the warning, chose the ground, and rallied frightened people until the attackers broke against a defence they had not expected."), (args, u) => { u.UpgradeLeadershipTacticsSkills(args, DefaultCharacterAttributes.Cunning); args.SetRenownToAdd(20); }, ccm => IsNorthman(ccm) && (NarrativeChoiceState.YouthWas("northman_youth_hall_retainer_option", "northman_youth_levy_option", "northman_youth_shieldwoman_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_drafted_to_war_pose"));
        yield return new NarrativeOption("northman_adulthood_winter_relief_option", new TextObject("{=bab_northman_adulthood_winter_relief_title}you brought a hungry settlement through winter."), new TextObject("{=bab_northman_adulthood_winter_relief_desc}You found hidden stores, imposed fair rationing, and organized dangerous journeys for food and fuel until the thaw returned."), (args, u) => { u.UpgradeLeadershipStewardSkills(args, DefaultCharacterAttributes.Intelligence); args.SetRenownToAdd(15); }, ccm => IsNorthman(ccm) && (NarrativeChoiceState.YouthWas("northman_youth_winter_steward_option", "northman_youth_wanderer_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_decisive"));
        yield return new NarrativeOption("northman_adulthood_great_hunt_option", new TextObject("{=bab_northman_adulthood_great_hunt_title}you slew a beast that threatened the settlements."), new TextObject("{=bab_northman_adulthood_great_hunt_desc}You tracked the animal through forest and snow and brought it down before it could take more livestock or lives."), (args, u) => { u.UpgradeScoutingBowSkills(args, DefaultCharacterAttributes.Control); args.SetRenownToAdd(10); }, ccm => IsNorthman(ccm) && (NarrativeChoiceState.YouthWas("northman_youth_woodsman_option", "northman_youth_wanderer_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_tough"));
        yield return new NarrativeOption("northman_adulthood_winter_melee_option", new TextObject("{=bab_northman_adulthood_winter_melee_title}you won renown in a northern melee."), new TextObject("{=bab_northman_adulthood_winter_melee_desc}Northern lords cared less for the tilt than many southern knights. In the crush of a melee, you proved your courage and mastery of shield and steel."), (args, u) => { u.UpgradeOneHandedTwoHandedSkills(args, DefaultCharacterAttributes.Vigor); args.SetRenownToAdd(20); }, ccm => IsNorthman(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && NarrativeChoiceState.YouthWas("northman_youth_hall_retainer_option", "northman_youth_levy_option") || CharacterObject.PlayerCharacter.IsFemale && NarrativeChoiceState.YouthWas("northman_youth_shieldwoman_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_athlete"));
        yield return new NarrativeOption("northman_adulthood_lord_service_option", new TextObject("{=bab_northman_adulthood_lord_service_title}you earned a northern lord's trust."), new TextObject("{=bab_northman_adulthood_lord_service_desc}You carried difficult orders, judged local quarrels, and returned with results, becoming known as someone whose word and endurance could be relied upon."), (args, u) => { u.UpgradeLeadershipCharmSkills(args, DefaultCharacterAttributes.Social); args.SetRenownToAdd(15); }, ccm => IsNorthman(ccm) && (NarrativeChoiceState.YouthWas("northman_youth_hall_retainer_option", "northman_youth_winter_steward_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_manners"));
    }

    private static bool IsNorthman(CharacterCreationManager ccm) => ccm.CharacterCreationContent.SelectedCulture.StringId == "northman";

    private static NarrativeOption CreateParentOption(string id, string titleText, string descriptionText, System.Action<NarrativeMenuOptionArgs, NarrativeSkillUpgrades> setArgs, string occupationType, string motherAnimation, string fatherAnimation)
    {
        return new NarrativeOption(id, new TextObject(titleText), new TextObject(descriptionText), setArgs, IsNorthman, ccm =>
        {
            ccm.CharacterCreationContent.SetParentOccupation(occupationType);
            string cultureId = ccm.CharacterCreationContent.SelectedCulture.StringId;
            string motherEquipmentId = NarrativeEquipmentHelper.GetMotherEquipmentId(ccm, occupationType, cultureId);
            string fatherEquipmentId = NarrativeEquipmentHelper.GetFatherEquipmentId(ccm, occupationType, cultureId);
            NarrativeEquipmentHelper.SetParentEquipment(ccm, motherEquipmentId, fatherEquipmentId, motherAnimation, fatherAnimation);
        });
    }

    private void SelectYouth(CharacterCreationManager ccm, string titleType, string animation)
    {
        ccm.CharacterCreationContent.SelectedTitleType = titleType;
        string playerEquipmentId = NarrativeEquipmentHelper.GetPlayerEquipmentId(ccm, titleType, CultureId, Hero.MainHero.IsFemale);
        NarrativeEquipmentHelper.SetPlayerEquipment(ccm, playerEquipmentId, animation);
    }
}
