using System.Collections.Generic;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.CharacterCreationContent;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.Core;
using TaleWorlds.Localization;

namespace BloodAndBittersteel.Features.CharacterCreation.Cultures;

public class ReachmanCulture : ICharacterCreationCulture
{
    public string CultureId => "reachman";

    public IEnumerable<NarrativeOption> GetParentOptions()
    {
        yield return CreateParentOption("reachman_retainer_option", "{=bab_crownlander_parent_retainer_title}A lord's retainers", "{=bab_reachman_parent_retainer_desc}Your family served in a Reach lord's household, keeping his rich estates productive and his numerous levies prepared.", (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Social), CharacterOccupations.Retainer, "act_character_creation_female_default_side_to_side_1", "act_character_creation_male_default_side_to_side_1");
        yield return CreateParentOption("reachman_merchant_option", "{=651FhzdR}Urban merchants", "{=bab_reachman_parent_merchant_desc}Your family traded grain, wine, fruit, and fine goods between the Reach's prosperous towns and river ports.", (args, u) => u.UpgradeTradeCharmSkills(args, DefaultCharacterAttributes.Intelligence), CharacterOccupations.MerchantUrban, "act_character_creation_female_default_mother_front", "act_character_creation_male_default_mother_front");
        yield return CreateParentOption("reachman_farmer_option", "{=RDfXuVxT}Yeomen", "{=bab_reachman_parent_farmer_desc}Your family were prosperous smallholders in the fertile Reach, raising abundant crops and serving in the local levy.", (args, u) => u.UpgradePolearmCrossbowSkills(args, DefaultCharacterAttributes.Endurance), CharacterOccupations.Farmer, "act_character_creation_female_default_father_sitting", "act_character_creation_male_default_father_sitting");
        yield return CreateParentOption("reachman_blacksmith_option", "{=p2KIhGbE}Urban blacksmith", "{=bab_reachman_parent_blacksmith_desc}Your family owned a busy smithy, supplying farms with tools and knights and men-at-arms with weapons and horseshoes.", (args, u) => u.UpgradeCraftingTwoHandedSkills(args, DefaultCharacterAttributes.Vigor), CharacterOccupations.ArtisanUrban, "act_character_creation_female_default_side_to_side_2", "act_character_creation_male_default_side_to_side_2");
        yield return CreateParentOption("reachman_hunter_option", "{=YcnK0Thk}Hunters", "{=bab_reachman_parent_hunter_desc}Your family hunted the Reach's woods and managed game for nearby estates while avoiding the wrath of noble foresters.", (args, u) => u.UpgradeScoutingCrossbowSkills(args, DefaultCharacterAttributes.Control), CharacterOccupations.Hunter, "act_character_creation_female_default_side_to_side_3", "act_character_creation_male_default_side_to_side_3");
    }

    public IEnumerable<NarrativeOption> GetChildhoodOptions()
    {
        foreach (NarrativeOption option in MainlandChildhoodOptions.Shared)
            yield return option;

        yield return new NarrativeOption("reachman_childhood_tourney_games_option", new TextObject("{=bab_reachman_childhood_tourney_games_title}played at tourneys and knighthood."), new TextObject("{=bab_reachman_childhood_tourney_games_desc}You and the other children made wicker shields, chose queens of love and beauty, and reenacted famous tilts until every hedge became a list."), (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsReachman(ccm), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_childhood_character", "act_childhood_apprentice"));
    }

    public IEnumerable<NarrativeOption> GetEducationOptions()
    {
        foreach (NarrativeOption option in MainlandEducationOptions.Shared)
            yield return option;

        yield return new NarrativeOption("reachman_education_tourney_page_option", new TextObject("{=bab_reachman_education_tourney_page_title}served at tourneys and noble musters."), new TextObject("{=bab_reachman_education_tourney_page_desc}You waited upon knights during tourneys and musters, caring for horses and harness while observing how reputation, courtesy, and skill at arms advanced a young retainer."), (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsReachman(ccm) && ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer && !CharacterObject.PlayerCharacter.IsFemale, ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_apprentice", "", ""));
        yield return new NarrativeOption("reachman_education_reach_lady_option", new TextObject("{=bab_reachman_education_reach_lady_title}joined a great lady's household."), new TextObject("{=bab_reachman_education_reach_lady_desc}You served among a noblewoman's companions, learning music, letters, household accounts, and the alliances and rivalries concealed beneath courtly courtesy."), (args, u) => u.UpgradeStewardCharmSkills(args, DefaultCharacterAttributes.Social), ccm => IsReachman(ccm) && ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer && CharacterObject.PlayerCharacter.IsFemale, ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_manners", "", ""));
        yield return new NarrativeOption("reachman_education_estate_granaries_option", new TextObject("{=bab_reachman_education_estate_granaries_title}helped manage the estate granaries."), new TextObject("{=bab_reachman_education_estate_granaries_desc}The Reach's abundance required careful hands. You learned to reckon seed, rents, harvests, storage losses, and the wagons needed to feed a lord's household and host."), (args, u) => u.UpgradeLeadershipStewardSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsReachman(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.MerchantUrban), ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_book", "", ""));
    }

    public IEnumerable<NarrativeOption> GetYouthOptions()
    {
        foreach (NarrativeOption option in WesterosiSharedPathOptions.YouthOptions)
            yield return option;

        yield return new NarrativeOption("reachman_youth_squire_option", new TextObject("{=bab_reachman_youth_squire_title}served a knight as page and squire."), new TextObject("{=bab_reachman_youth_squire_desc}Through your family's service you entered the flowered courts and tourney grounds of the Reach, carrying messages, tending horses and harness, and training beneath an experienced knight."), (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsReachman(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer || NarrativeChoiceState.ChildhoodWas("childhood_horse_option", "reachman_childhood_tourney_games_option") || NarrativeChoiceState.EducationWas("reachman_education_tourney_page_option"))), ccm => SelectYouth(ccm, "noble", "act_childhood_apprentice"));
        yield return new NarrativeOption("reachman_youth_levy_option", new TextObject("{=bab_reachman_youth_levy_title}trained with the local levy."), new TextObject("{=bab_reachman_youth_levy_desc}You drilled with the spears, shields, and bows used by the smallfolk of the Reach, learning to hold formation when fear and noise broke less disciplined ranks."), (args, u) => u.UpgradePolearmOneHandedSkills(args, DefaultCharacterAttributes.Vigor), ccm => IsReachman(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban || NarrativeChoiceState.ChildhoodWas("childhood_brawn_option"))), ccm => SelectYouth(ccm, "infantry", "act_childhood_fierce"));
        yield return new NarrativeOption("reachman_youth_scout_option", new TextObject("{=bab_reachman_youth_scout_title}ranged ahead of travellers and hunting parties."), new TextObject("{=bab_reachman_youth_scout_desc}Your knowledge of orchards, broad fields, and busy roads made you useful as a guide and scout, watching for broken tracks, hostile riders, and safe ground ahead."), (args, u) => u.UpgradeScoutingBowSkills(args, DefaultCharacterAttributes.Cunning), ccm => IsReachman(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Hunter || NarrativeChoiceState.ChildhoodWas("childhood_detail_option", "reachman_childhood_tourney_games_option")), ccm => SelectYouth(ccm, "skirmisher", "act_childhood_fox"));
        yield return new NarrativeOption("reachman_youth_courtier_option", new TextObject("{=bab_reachman_youth_courtier_title}learned to survive the intrigues of a noble court."), new TextObject("{=bab_reachman_youth_courtier_desc}You remained among the flowered courts and tourney grounds of the Reach, mastering household accounts, correspondence, courtesy, and the alliances hidden beneath feasts and ceremonies."), (args, u) => u.UpgradeStewardCharmSkills(args, DefaultCharacterAttributes.Social), ccm => IsReachman(ccm) && (CharacterObject.PlayerCharacter.IsFemale && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer || NarrativeChoiceState.EducationWas("education_retainer_lady_option", "reachman_education_reach_lady_option"))), ccm => SelectYouth(ccm, "noble", "act_childhood_manners"));
        yield return new NarrativeOption("reachman_youth_factor_option", new TextObject("{=bab_reachman_youth_factor_title}acted as a young factor for your family."), new TextObject("{=bab_reachman_youth_factor_desc}You travelled through the Reach's granaries, vineyards, and market towns, inspecting goods, keeping accounts, and bargaining with people who respected profit more than birth."), (args, u) => u.UpgradeTradeCharmSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsReachman(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.MerchantUrban || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer), ccm => SelectYouth(ccm, "merchant", "act_childhood_book"));
        yield return new NarrativeOption("reachman_youth_rebellious_option", new TextObject("{=bab_reachman_youth_rebellious_title}trained secretly with horse and arms."), new TextObject("{=bab_reachman_youth_rebellious_desc}The customs of the Reach did not expect you to become a warrior. You borrowed time, weapons, and instruction wherever you could, refusing to let that judgment decide your life."), (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsReachman(ccm) && (CharacterObject.PlayerCharacter.IsFemale && (NarrativeChoiceState.ChildhoodWas("childhood_brawn_option", "childhood_horse_option", "reachman_childhood_tourney_games_option") || NarrativeChoiceState.EducationWas("education_retainer_stables_option"))), ccm => SelectYouth(ccm, "cavalry", "act_childhood_fierce"));
    }

    public IEnumerable<NarrativeOption> GetAdulthoodOptions()
    {
        foreach (NarrativeOption option in WesterosiSharedPathOptions.AdulthoodOptions)
            yield return option;

        yield return new NarrativeOption("reachman_adulthood_vineyard_option", new TextObject("{=bab_reachman_adulthood_vineyard_title}you restored a vineyard and cider press."), new TextObject("{=bab_reachman_adulthood_vineyard_desc}You pruned neglected vines and orchards, repaired presses and casks, and brought a spoiled holding back to a profitable harvest."), (args, u) => { u.UpgradeTradeCraftingSkills(args, DefaultCharacterAttributes.Intelligence); args.SetRenownToAdd(10); }, ccm => IsReachman(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer || NarrativeChoiceState.YouthWas("westerosi_youth_family_farm_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_grit"));
        yield return new NarrativeOption("reachman_adulthood_tourney_supplier_option", new TextObject("{=bab_reachman_adulthood_tourney_supplier_title}you supplied tourneys and great feasts."), new TextObject("{=bab_reachman_adulthood_tourney_supplier_desc}You brought tents, fodder, wine, food, timber, and countless small necessities to gatherings where knights won glory and merchants quietly made fortunes."), (args, u) => { u.UpgradeTradeLeadershipSkills(args, DefaultCharacterAttributes.Social); args.SetRenownToAdd(10); }, ccm => IsReachman(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.MerchantUrban || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban || NarrativeChoiceState.YouthWas("westerosi_youth_caravan_hand_option", "westerosi_youth_family_workshop_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_decisive"));

        yield return new NarrativeOption("reachman_adulthood_tourney_knight_option", new TextObject("{=bab_reachman_adulthood_tourney_knight_title}you travelled the tourney circuit as a knight."), new TextObject("{=bab_reachman_adulthood_tourney_knight_desc}With horse, armour, and hard-won skill, you rode from one tourney in Westeros to the next, testing yourself in melees and lists while seeking ransom, patronage, and renown."), (args, u) => { u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance); args.SetRenownToAdd(20); }, ccm => IsReachman(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && NarrativeChoiceState.YouthWas("reachman_youth_squire_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_apprentice"));
        yield return new NarrativeOption("reachman_adulthood_mystery_knight_option", new TextObject("{=bab_reachman_adulthood_mystery_knight_title}you entered the lists as a mystery knight."), new TextObject("{=bab_reachman_adulthood_mystery_knight_desc}Hidden behind an unknown device and a closed helm, you defied custom and entered the lists. Whatever the heralds guessed, your courage and skill could not be dismissed."), (args, u) => { u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance); args.SetRenownToAdd(20); }, ccm => IsReachman(ccm) && (CharacterObject.PlayerCharacter.IsFemale && NarrativeChoiceState.YouthWas("reachman_youth_rebellious_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_fierce"));
        yield return new NarrativeOption("reachman_adulthood_campaign_option", new TextObject("{=bab_reachman_adulthood_campaign_title}you distinguished yourself during a local campaign."), new TextObject("{=bab_reachman_adulthood_campaign_desc}When banners were called in the Reach, you marched with the host and kept your courage when scouting, skirmishing, and hard close fighting replaced youthful drills."), (args, u) => { u.UpgradeLeadershipTacticsSkills(args, DefaultCharacterAttributes.Cunning); args.SetRenownToAdd(15); }, ccm => IsReachman(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && NarrativeChoiceState.YouthWas("reachman_youth_levy_option", "reachman_youth_scout_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_drafted_to_war_pose"));
        yield return new NarrativeOption("reachman_adulthood_court_service_option", new TextObject("{=bab_reachman_adulthood_court_service_title}you won influence in a great household."), new TextObject("{=bab_reachman_adulthood_court_service_desc}Your judgment, discretion, and command of household politics earned you trust in the flowered courts and tourney grounds of the Reach, and people began seeking your help before presenting delicate requests."), (args, u) => { u.UpgradeStewardCharmSkills(args, DefaultCharacterAttributes.Social); args.SetRenownToAdd(10); }, ccm => IsReachman(ccm) && (NarrativeChoiceState.YouthWas("reachman_youth_courtier_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_manners"));
        yield return new NarrativeOption("reachman_adulthood_trade_venture_option", new TextObject("{=bab_reachman_adulthood_trade_venture_title}you completed a profitable trading venture."), new TextObject("{=bab_reachman_adulthood_trade_venture_desc}You organized credit, guards, transport, and buyers for a venture through the Reach's granaries, vineyards, and market towns, returning with both profit and a reputation for sound judgment."), (args, u) => { u.UpgradeTradeLeadershipSkills(args, DefaultCharacterAttributes.Intelligence); args.SetRenownToAdd(10); }, ccm => IsReachman(ccm) && (NarrativeChoiceState.YouthWas("reachman_youth_factor_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_decisive"));
        yield return new NarrativeOption("reachman_adulthood_border_deed_option", new TextObject("{=bab_reachman_adulthood_border_deed_title}you protected travellers from outlaws."), new TextObject("{=bab_reachman_adulthood_border_deed_desc}Your knowledge of orchards, broad fields, and busy roads let you find an outlaw band that had preyed upon local travellers. You guided armed men to its camp and helped break it."), (args, u) => { u.UpgradeScoutingTacticsSkills(args, DefaultCharacterAttributes.Cunning); args.SetRenownToAdd(10); }, ccm => IsReachman(ccm) && (NarrativeChoiceState.YouthWas("reachman_youth_scout_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_tough"));
    }

    private static bool IsReachman(CharacterCreationManager ccm) => ccm.CharacterCreationContent.SelectedCulture.StringId == "reachman";

    private static NarrativeOption CreateParentOption(string id, string titleText, string descriptionText, System.Action<NarrativeMenuOptionArgs, NarrativeSkillUpgrades> setArgs, string occupationType, string motherAnimation, string fatherAnimation)
    {
        return new NarrativeOption(id, new TextObject(titleText), new TextObject(descriptionText), setArgs, IsReachman, ccm =>
        {
            ccm.CharacterCreationContent.SetParentOccupation(occupationType);
            string cultureId = ccm.CharacterCreationContent.SelectedCulture.StringId;
            string motherEquipmentId = NarrativeEquipmentHelper.GetMotherEquipmentId(ccm, occupationType, cultureId);
            string fatherEquipmentId = NarrativeEquipmentHelper.GetFatherEquipmentId(ccm, occupationType, cultureId);
            NarrativeEquipmentHelper.SetParentEquipment(ccm, motherEquipmentId, fatherEquipmentId, motherAnimation, fatherAnimation);
        });
    }

    private void SelectYouth(CharacterCreationManager ccm, string titleType, string animation)
    {
        ccm.CharacterCreationContent.SelectedTitleType = titleType;
        string playerEquipmentId = NarrativeEquipmentHelper.GetPlayerEquipmentId(ccm, titleType, CultureId, Hero.MainHero.IsFemale);
        NarrativeEquipmentHelper.SetPlayerEquipment(ccm, playerEquipmentId, animation);
    }
}
