using System.Collections.Generic;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.CharacterCreationContent;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.Core;
using TaleWorlds.Localization;

namespace BloodAndBittersteel.Features.CharacterCreation.Cultures;

public class RiverlanderCulture : ICharacterCreationCulture
{
    public string CultureId => "riverlander";

    public IEnumerable<NarrativeOption> GetParentOptions()
    {
        yield return CreateParentOption("riverlander_retainer_option", "{=bab_crownlander_parent_retainer_title}A lord's retainers", "{=bab_riverlander_parent_retainer_desc}Your family served a river lord, settling disputes among tenants and mustering men to defend ford, ferry, and field.", (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Social), CharacterOccupations.Retainer, "act_character_creation_female_default_side_to_side_1", "act_character_creation_male_default_side_to_side_1");
        yield return CreateParentOption("riverlander_merchant_option", "{=651FhzdR}Urban merchants", "{=bab_riverlander_parent_merchant_desc}Your family carried grain, fish, timber, and wool along the river roads and waterways of the Trident.", (args, u) => u.UpgradeTradeCharmSkills(args, DefaultCharacterAttributes.Intelligence), CharacterOccupations.MerchantUrban, "act_character_creation_female_default_mother_front", "act_character_creation_male_default_mother_front");
        yield return CreateParentOption("riverlander_farmer_option", "{=RDfXuVxT}Yeomen", "{=bab_riverlander_parent_farmer_desc}Your family farmed the rich but often-contested soil of the riverlands and learned to rebuild after passing armies.", (args, u) => u.UpgradePolearmCrossbowSkills(args, DefaultCharacterAttributes.Endurance), CharacterOccupations.Farmer, "act_character_creation_female_default_father_sitting", "act_character_creation_male_default_father_sitting");
        yield return CreateParentOption("riverlander_blacksmith_option", "{=p2KIhGbE}Urban blacksmith", "{=bab_riverlander_parent_blacksmith_desc}Your family owned a town forge, repairing ploughs in peace and making spearheads and horseshoes whenever war returned.", (args, u) => u.UpgradeCraftingTwoHandedSkills(args, DefaultCharacterAttributes.Vigor), CharacterOccupations.ArtisanUrban, "act_character_creation_female_default_side_to_side_2", "act_character_creation_male_default_side_to_side_2");
        yield return CreateParentOption("riverlander_hunter_option", "{=YcnK0Thk}Hunters", "{=bab_riverlander_parent_hunter_desc}Your family hunted beside rivers, marshes, and woods, becoming skilled trackers and boatmen.", (args, u) => u.UpgradeScoutingCrossbowSkills(args, DefaultCharacterAttributes.Control), CharacterOccupations.Hunter, "act_character_creation_female_default_side_to_side_3", "act_character_creation_male_default_side_to_side_3");
    }

    public IEnumerable<NarrativeOption> GetChildhoodOptions()
    {
        foreach (NarrativeOption option in MainlandChildhoodOptions.Shared)
            yield return option;

        yield return new NarrativeOption("riverlander_childhood_river_child_option", new TextObject("{=bab_riverlander_childhood_river_child_title}learned every ford and ferry nearby."), new TextObject("{=bab_riverlander_childhood_river_child_desc}You swam, fished, and poled small boats along the shallows, learning how quickly a familiar river changed after rain."), (args, u) => u.UpgradeScoutingTacticsSkills(args, DefaultCharacterAttributes.Cunning), ccm => IsRiverlander(ccm), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_childhood_character", "act_childhood_fox"));
    }

    public IEnumerable<NarrativeOption> GetEducationOptions()
    {
        foreach (NarrativeOption option in MainlandEducationOptions.Shared)
            yield return option;

        yield return new NarrativeOption("riverlander_education_ferry_accounts_option", new TextObject("{=bab_riverlander_education_ferry_accounts_title}collected tolls at a ferry or bridge."), new TextObject("{=bab_riverlander_education_ferry_accounts_desc}You helped reckon cargoes, collect lawful tolls, and judge when flood or war made a crossing too dangerous for travellers and wagons."), (args, u) => u.UpgradeEngineeringTradeSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsRiverlander(ccm) && ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.MerchantUrban, ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_book", "", ""));
        yield return new NarrativeOption("riverlander_education_river_works_option", new TextObject("{=bab_riverlander_education_river_works_title}maintained dikes, mills, and watercourses."), new TextObject("{=bab_riverlander_education_river_works_desc}You laboured where river met field, learning how banks, sluices, millraces, and drainage ditches protected crops and kept a community fed."), (args, u) => u.UpgradeCraftingEngineeringSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsRiverlander(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban), ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_grit", "", ""));
        yield return new NarrativeOption("riverlander_education_river_ward_option", new TextObject("{=bab_riverlander_education_river_ward_title}were fostered in another river lord's hall."), new TextObject("{=bab_riverlander_education_river_ward_desc}Your family sent you to a neighbouring hall, where service beside other wards taught you courtesy, local loyalties, and how quickly friendship could become alliance in the riverlands."), (args, u) => u.UpgradeLeadershipCharmSkills(args, DefaultCharacterAttributes.Social), ccm => IsRiverlander(ccm) && ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer, ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_manners", "", ""));
    }

    public IEnumerable<NarrativeOption> GetYouthOptions()
    {
        foreach (NarrativeOption option in WesterosiSharedPathOptions.YouthOptions)
            yield return option;

        yield return new NarrativeOption("riverlander_youth_squire_option", new TextObject("{=bab_riverlander_youth_squire_title}served a knight as page and squire."), new TextObject("{=bab_riverlander_youth_squire_desc}Through your family's service you entered the halls guarding the Trident's crossings, carrying messages, tending horses and harness, and training beneath an experienced knight."), (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsRiverlander(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer || NarrativeChoiceState.ChildhoodWas("childhood_horse_option", "riverlander_childhood_river_child_option") || NarrativeChoiceState.EducationWas("riverlander_education_river_ward_option"))), ccm => SelectYouth(ccm, "noble", "act_childhood_apprentice"));
        yield return new NarrativeOption("riverlander_youth_levy_option", new TextObject("{=bab_riverlander_youth_levy_title}trained with the local levy."), new TextObject("{=bab_riverlander_youth_levy_desc}You drilled with the spears, shields, and bows used by the smallfolk of the riverlands, learning to hold formation when fear and noise broke less disciplined ranks."), (args, u) => u.UpgradePolearmOneHandedSkills(args, DefaultCharacterAttributes.Vigor), ccm => IsRiverlander(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban || NarrativeChoiceState.ChildhoodWas("childhood_brawn_option"))), ccm => SelectYouth(ccm, "infantry", "act_childhood_fierce"));
        yield return new NarrativeOption("riverlander_youth_scout_option", new TextObject("{=bab_riverlander_youth_scout_title}ranged ahead of travellers and hunting parties."), new TextObject("{=bab_riverlander_youth_scout_desc}Your knowledge of rivers, willow woods, and disputed roads made you useful as a guide and scout, watching for broken tracks, hostile riders, and safe ground ahead."), (args, u) => u.UpgradeScoutingBowSkills(args, DefaultCharacterAttributes.Cunning), ccm => IsRiverlander(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Hunter || NarrativeChoiceState.ChildhoodWas("childhood_detail_option", "riverlander_childhood_river_child_option")), ccm => SelectYouth(ccm, "skirmisher", "act_childhood_fox"));
        yield return new NarrativeOption("riverlander_youth_courtier_option", new TextObject("{=bab_riverlander_youth_courtier_title}learned to survive the intrigues of a noble court."), new TextObject("{=bab_riverlander_youth_courtier_desc}You remained among the halls guarding the Trident's crossings, mastering household accounts, correspondence, courtesy, and the alliances hidden beneath feasts and ceremonies."), (args, u) => u.UpgradeStewardCharmSkills(args, DefaultCharacterAttributes.Social), ccm => IsRiverlander(ccm) && (CharacterObject.PlayerCharacter.IsFemale && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer || NarrativeChoiceState.EducationWas("education_retainer_lady_option"))), ccm => SelectYouth(ccm, "noble", "act_childhood_manners"));
        yield return new NarrativeOption("riverlander_youth_factor_option", new TextObject("{=bab_riverlander_youth_factor_title}acted as a young factor for your family."), new TextObject("{=bab_riverlander_youth_factor_desc}You travelled through ferries, mills, and riverside markets, inspecting goods, keeping accounts, and bargaining with people who respected profit more than birth."), (args, u) => u.UpgradeTradeCharmSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsRiverlander(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.MerchantUrban || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer), ccm => SelectYouth(ccm, "merchant", "act_childhood_book"));
        yield return new NarrativeOption("riverlander_youth_rebellious_option", new TextObject("{=bab_riverlander_youth_rebellious_title}trained secretly with horse and arms."), new TextObject("{=bab_riverlander_youth_rebellious_desc}The customs of the riverlands did not expect you to become a warrior. You borrowed time, weapons, and instruction wherever you could, refusing to let that judgment decide your life."), (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsRiverlander(ccm) && (CharacterObject.PlayerCharacter.IsFemale && (NarrativeChoiceState.ChildhoodWas("childhood_brawn_option", "childhood_horse_option", "riverlander_childhood_river_child_option") || NarrativeChoiceState.EducationWas("education_retainer_stables_option"))), ccm => SelectYouth(ccm, "cavalry", "act_childhood_fierce"));
    }

    public IEnumerable<NarrativeOption> GetAdulthoodOptions()
    {
        foreach (NarrativeOption option in WesterosiSharedPathOptions.AdulthoodOptions)
            yield return option;

        yield return new NarrativeOption("riverlander_adulthood_trident_seasons_option", new TextObject("{=bab_riverlander_adulthood_trident_seasons_title}you followed the Trident's floods and planting seasons."), new TextObject("{=bab_riverlander_adulthood_trident_seasons_desc}You moved where levees needed mending, seed needed sowing, or harvest hands were scarce, learning how every ford and field changed with the rivers."), (args, u) => { u.UpgradeAthleticsTradeSkills(args, DefaultCharacterAttributes.Endurance); args.SetRenownToAdd(5); }, ccm => IsRiverlander(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer || NarrativeChoiceState.YouthWas("westerosi_youth_family_farm_option", "westerosi_youth_road_wanderer_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_peddlers"));

        yield return new NarrativeOption("riverlander_adulthood_tourney_knight_option", new TextObject("{=bab_riverlander_adulthood_tourney_knight_title}you travelled the tourney circuit as a knight."), new TextObject("{=bab_riverlander_adulthood_tourney_knight_desc}With horse, armour, and hard-won skill, you rode from one tourney in Westeros to the next, testing yourself in melees and lists while seeking ransom, patronage, and renown."), (args, u) => { u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance); args.SetRenownToAdd(20); }, ccm => IsRiverlander(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && NarrativeChoiceState.YouthWas("riverlander_youth_squire_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_apprentice"));
        yield return new NarrativeOption("riverlander_adulthood_mystery_knight_option", new TextObject("{=bab_riverlander_adulthood_mystery_knight_title}you entered the lists as a mystery knight."), new TextObject("{=bab_riverlander_adulthood_mystery_knight_desc}Hidden behind an unknown device and a closed helm, you defied custom and entered the lists. Whatever the heralds guessed, your courage and skill could not be dismissed."), (args, u) => { u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance); args.SetRenownToAdd(20); }, ccm => IsRiverlander(ccm) && (CharacterObject.PlayerCharacter.IsFemale && NarrativeChoiceState.YouthWas("riverlander_youth_rebellious_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_fierce"));
        yield return new NarrativeOption("riverlander_adulthood_campaign_option", new TextObject("{=bab_riverlander_adulthood_campaign_title}you distinguished yourself during a local campaign."), new TextObject("{=bab_riverlander_adulthood_campaign_desc}When banners were called in the riverlands, you marched with the host and kept your courage when scouting, skirmishing, and hard close fighting replaced youthful drills."), (args, u) => { u.UpgradeLeadershipTacticsSkills(args, DefaultCharacterAttributes.Cunning); args.SetRenownToAdd(15); }, ccm => IsRiverlander(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && NarrativeChoiceState.YouthWas("riverlander_youth_levy_option", "riverlander_youth_scout_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_drafted_to_war_pose"));
        yield return new NarrativeOption("riverlander_adulthood_court_service_option", new TextObject("{=bab_riverlander_adulthood_court_service_title}you won influence in a great household."), new TextObject("{=bab_riverlander_adulthood_court_service_desc}Your judgment, discretion, and command of household politics earned you trust in the halls guarding the Trident's crossings, and people began seeking your help before presenting delicate requests."), (args, u) => { u.UpgradeStewardCharmSkills(args, DefaultCharacterAttributes.Social); args.SetRenownToAdd(10); }, ccm => IsRiverlander(ccm) && (NarrativeChoiceState.YouthWas("riverlander_youth_courtier_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_manners"));
        yield return new NarrativeOption("riverlander_adulthood_trade_venture_option", new TextObject("{=bab_riverlander_adulthood_trade_venture_title}you completed a profitable trading venture."), new TextObject("{=bab_riverlander_adulthood_trade_venture_desc}You organized credit, guards, transport, and buyers for a venture through ferries, mills, and riverside markets, returning with both profit and a reputation for sound judgment."), (args, u) => { u.UpgradeTradeLeadershipSkills(args, DefaultCharacterAttributes.Intelligence); args.SetRenownToAdd(10); }, ccm => IsRiverlander(ccm) && (NarrativeChoiceState.YouthWas("riverlander_youth_factor_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_decisive"));
        yield return new NarrativeOption("riverlander_adulthood_border_deed_option", new TextObject("{=bab_riverlander_adulthood_border_deed_title}you protected travellers from outlaws."), new TextObject("{=bab_riverlander_adulthood_border_deed_desc}Your knowledge of rivers, willow woods, and disputed roads let you find an outlaw band that had preyed upon local travellers. You guided armed men to its camp and helped break it."), (args, u) => { u.UpgradeScoutingTacticsSkills(args, DefaultCharacterAttributes.Cunning); args.SetRenownToAdd(10); }, ccm => IsRiverlander(ccm) && (NarrativeChoiceState.YouthWas("riverlander_youth_scout_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_tough"));
    }

    private static bool IsRiverlander(CharacterCreationManager ccm) => ccm.CharacterCreationContent.SelectedCulture.StringId == "riverlander";

    private static NarrativeOption CreateParentOption(string id, string titleText, string descriptionText, System.Action<NarrativeMenuOptionArgs, NarrativeSkillUpgrades> setArgs, string occupationType, string motherAnimation, string fatherAnimation)
    {
        return new NarrativeOption(id, new TextObject(titleText), new TextObject(descriptionText), setArgs, IsRiverlander, ccm =>
        {
            ccm.CharacterCreationContent.SetParentOccupation(occupationType);
            string cultureId = ccm.CharacterCreationContent.SelectedCulture.StringId;
            string motherEquipmentId = NarrativeEquipmentHelper.GetMotherEquipmentId(ccm, occupationType, cultureId);
            string fatherEquipmentId = NarrativeEquipmentHelper.GetFatherEquipmentId(ccm, occupationType, cultureId);
            NarrativeEquipmentHelper.SetParentEquipment(ccm, motherEquipmentId, fatherEquipmentId, motherAnimation, fatherAnimation);
        });
    }

    private void SelectYouth(CharacterCreationManager ccm, string titleType, string animation)
    {
        ccm.CharacterCreationContent.SelectedTitleType = titleType;
        string playerEquipmentId = NarrativeEquipmentHelper.GetPlayerEquipmentId(ccm, titleType, CultureId, Hero.MainHero.IsFemale);
        NarrativeEquipmentHelper.SetPlayerEquipment(ccm, playerEquipmentId, animation);
    }
}
