using System.Collections.Generic;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.CharacterCreationContent;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.Core;
using TaleWorlds.Localization;

namespace BloodAndBittersteel.Features.CharacterCreation.Cultures;

public class StormlanderCulture : ICharacterCreationCulture
{
    public string CultureId => "stormlander";

    public IEnumerable<NarrativeOption> GetParentOptions()
    {
        yield return CreateParentOption("stormlander_retainer_option", "{=bab_crownlander_parent_retainer_title}A lord's retainers", "{=bab_stormlander_parent_retainer_desc}Your family served a storm lord, overseeing his household and mustering the hard folk of the rainwood when banners were called.", (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Social), CharacterOccupations.Retainer, "act_character_creation_female_default_side_to_side_1", "act_character_creation_male_default_side_to_side_1");
        yield return CreateParentOption("stormlander_merchant_option", "{=651FhzdR}Urban merchants", "{=bab_stormlander_parent_merchant_desc}Your family dealt in timber, grain, and goods landed at the storm coast's guarded harbours.", (args, u) => u.UpgradeTradeCharmSkills(args, DefaultCharacterAttributes.Intelligence), CharacterOccupations.MerchantUrban, "act_character_creation_female_default_mother_front", "act_character_creation_male_default_mother_front");
        yield return CreateParentOption("stormlander_farmer_option", "{=RDfXuVxT}Yeomen", "{=bab_stormlander_parent_farmer_desc}Your family worked stubborn soil beneath frequent storms and stood in the levy when raiders or rival lords threatened.", (args, u) => u.UpgradePolearmCrossbowSkills(args, DefaultCharacterAttributes.Endurance), CharacterOccupations.Farmer, "act_character_creation_female_default_father_sitting", "act_character_creation_male_default_father_sitting");
        yield return CreateParentOption("stormlander_blacksmith_option", "{=p2KIhGbE}Urban blacksmith", "{=bab_stormlander_parent_blacksmith_desc}Your family owned a town smithy and forged the sturdy tools and weapons demanded by life in the stormlands.", (args, u) => u.UpgradeCraftingTwoHandedSkills(args, DefaultCharacterAttributes.Vigor), CharacterOccupations.ArtisanUrban, "act_character_creation_female_default_side_to_side_2", "act_character_creation_male_default_side_to_side_2");
        yield return CreateParentOption("stormlander_hunter_option", "{=YcnK0Thk}Hunters", "{=bab_stormlander_parent_hunter_desc}Your family hunted beneath the dark boughs of the rainwood and knew how to endure its downpours and tangled paths.", (args, u) => u.UpgradeScoutingCrossbowSkills(args, DefaultCharacterAttributes.Control), CharacterOccupations.Hunter, "act_character_creation_female_default_side_to_side_3", "act_character_creation_male_default_side_to_side_3");
    }

    public IEnumerable<NarrativeOption> GetChildhoodOptions()
    {
        foreach (NarrativeOption option in MainlandChildhoodOptions.Shared)
            yield return option;

        yield return new NarrativeOption("stormlander_childhood_storm_child_option", new TextObject("{=bab_stormlander_childhood_storm_child_title}helped whenever the storms came."), new TextObject("{=bab_stormlander_childhood_storm_child_desc}When wind tore roofs and rain flooded yards, you carried timber, rope, and messages until the household was secure again."), (args, u) => u.UpgradeAthleticsCraftingSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsStormlander(ccm), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_childhood_character", "act_childhood_grit"));
    }

    public IEnumerable<NarrativeOption> GetEducationOptions()
    {
        foreach (NarrativeOption option in MainlandEducationOptions.Shared)
            yield return option;

        yield return new NarrativeOption("stormlander_education_storm_keep_option", new TextObject("{=bab_stormlander_education_storm_keep_title}served in a storm lord's household."), new TextObject("{=bab_stormlander_education_storm_keep_desc}You learned your duties in a rain-beaten castle, carrying orders between hall, stable, armoury, and gate while storms tested every roof and wall."), (args, u) => u.UpgradeLeadershipTacticsSkills(args, DefaultCharacterAttributes.Social), ccm => IsStormlander(ccm) && ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer, ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_manners", "", ""));
        yield return new NarrativeOption("stormlander_education_rainwood_option", new TextObject("{=bab_stormlander_education_rainwood_title}learned the ways of the rainwood."), new TextObject("{=bab_stormlander_education_rainwood_desc}You ranged beneath the wet green canopy, learning to follow game, cross swollen streams, keep bowstrings dry, and find paths hidden by rain and undergrowth."), (args, u) => u.UpgradeScoutingBowSkills(args, DefaultCharacterAttributes.Cunning), ccm => IsStormlander(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Hunter || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer), ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_sharp", "", ""));
        yield return new NarrativeOption("stormlander_education_castle_supplies_option", new TextObject("{=bab_stormlander_education_castle_supplies_title}provisioned castles against the storms."), new TextObject("{=bab_stormlander_education_castle_supplies_desc}You helped merchants and craftsmen move grain, timber, ironwork, and lamp oil into guarded storehouses before roads and harbours were closed by violent weather."), (args, u) => u.UpgradeTradeCraftingSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsStormlander(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.MerchantUrban || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban), ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_peddlers_2", "", ""));
    }

    public IEnumerable<NarrativeOption> GetYouthOptions()
    {
        foreach (NarrativeOption option in WesterosiSharedPathOptions.YouthOptions)
            yield return option;

        yield return new NarrativeOption("stormlander_youth_squire_option", new TextObject("{=bab_stormlander_youth_squire_title}served a knight as page and squire."), new TextObject("{=bab_stormlander_youth_squire_desc}Through your family's service you entered the rain-beaten keeps of the storm lords, carrying messages, tending horses and harness, and training beneath an experienced knight."), (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsStormlander(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer || NarrativeChoiceState.ChildhoodWas("childhood_horse_option", "stormlander_childhood_storm_child_option") || NarrativeChoiceState.EducationWas("stormlander_education_storm_keep_option"))), ccm => SelectYouth(ccm, "noble", "act_childhood_apprentice"));
        yield return new NarrativeOption("stormlander_youth_levy_option", new TextObject("{=bab_stormlander_youth_levy_title}trained with the local levy."), new TextObject("{=bab_stormlander_youth_levy_desc}You drilled with the spears, shields, and bows used by the smallfolk of the stormlands, learning to hold formation when fear and noise broke less disciplined ranks."), (args, u) => u.UpgradePolearmOneHandedSkills(args, DefaultCharacterAttributes.Vigor), ccm => IsStormlander(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban || NarrativeChoiceState.ChildhoodWas("childhood_brawn_option"))), ccm => SelectYouth(ccm, "infantry", "act_childhood_fierce"));
        yield return new NarrativeOption("stormlander_youth_scout_option", new TextObject("{=bab_stormlander_youth_scout_title}ranged ahead of travellers and hunting parties."), new TextObject("{=bab_stormlander_youth_scout_desc}Your knowledge of the rainwood, marches, and storm coast made you useful as a guide and scout, watching for broken tracks, hostile riders, and safe ground ahead."), (args, u) => u.UpgradeScoutingBowSkills(args, DefaultCharacterAttributes.Cunning), ccm => IsStormlander(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Hunter || NarrativeChoiceState.ChildhoodWas("childhood_detail_option", "stormlander_childhood_storm_child_option")), ccm => SelectYouth(ccm, "skirmisher", "act_childhood_fox"));
        yield return new NarrativeOption("stormlander_youth_courtier_option", new TextObject("{=bab_stormlander_youth_courtier_title}learned to survive the intrigues of a noble court."), new TextObject("{=bab_stormlander_youth_courtier_desc}You remained among the rain-beaten keeps of the storm lords, mastering household accounts, correspondence, courtesy, and the alliances hidden beneath feasts and ceremonies."), (args, u) => u.UpgradeStewardCharmSkills(args, DefaultCharacterAttributes.Social), ccm => IsStormlander(ccm) && (CharacterObject.PlayerCharacter.IsFemale && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer || NarrativeChoiceState.EducationWas("education_retainer_lady_option"))), ccm => SelectYouth(ccm, "noble", "act_childhood_manners"));
        yield return new NarrativeOption("stormlander_youth_factor_option", new TextObject("{=bab_stormlander_youth_factor_title}acted as a young factor for your family."), new TextObject("{=bab_stormlander_youth_factor_desc}You travelled through stormland ports and castle storehouses, inspecting goods, keeping accounts, and bargaining with people who respected profit more than birth."), (args, u) => u.UpgradeTradeCharmSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsStormlander(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.MerchantUrban || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer), ccm => SelectYouth(ccm, "merchant", "act_childhood_book"));
        yield return new NarrativeOption("stormlander_youth_rebellious_option", new TextObject("{=bab_stormlander_youth_rebellious_title}trained secretly with horse and arms."), new TextObject("{=bab_stormlander_youth_rebellious_desc}The customs of the stormlands did not expect you to become a warrior. You borrowed time, weapons, and instruction wherever you could, refusing to let that judgment decide your life."), (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsStormlander(ccm) && (CharacterObject.PlayerCharacter.IsFemale && (NarrativeChoiceState.ChildhoodWas("childhood_brawn_option", "childhood_horse_option", "stormlander_childhood_storm_child_option") || NarrativeChoiceState.EducationWas("education_retainer_stables_option"))), ccm => SelectYouth(ccm, "cavalry", "act_childhood_fierce"));
    }

    public IEnumerable<NarrativeOption> GetAdulthoodOptions()
    {
        foreach (NarrativeOption option in WesterosiSharedPathOptions.AdulthoodOptions)
            yield return option;

        yield return new NarrativeOption("stormlander_adulthood_storm_rebuilder_option", new TextObject("{=bab_stormlander_adulthood_storm_rebuilder_title}you rebuilt after a great storm."), new TextObject("{=bab_stormlander_adulthood_storm_rebuilder_desc}After wind and sea tore roofs away, smashed boats, and broke walls, you organized timber, stone, tools, and neighbors until the settlement stood again."), (args, u) => { u.UpgradeCraftingEngineeringSkills(args, DefaultCharacterAttributes.Endurance); args.SetRenownToAdd(10); }, ccm => IsStormlander(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer || NarrativeChoiceState.YouthWas("westerosi_youth_family_workshop_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_grit"));

        yield return new NarrativeOption("stormlander_adulthood_tourney_knight_option", new TextObject("{=bab_stormlander_adulthood_tourney_knight_title}you travelled the tourney circuit as a knight."), new TextObject("{=bab_stormlander_adulthood_tourney_knight_desc}With horse, armour, and hard-won skill, you rode from one tourney in Westeros to the next, testing yourself in melees and lists while seeking ransom, patronage, and renown."), (args, u) => { u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance); args.SetRenownToAdd(20); }, ccm => IsStormlander(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && NarrativeChoiceState.YouthWas("stormlander_youth_squire_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_apprentice"));
        yield return new NarrativeOption("stormlander_adulthood_mystery_knight_option", new TextObject("{=bab_stormlander_adulthood_mystery_knight_title}you entered the lists as a mystery knight."), new TextObject("{=bab_stormlander_adulthood_mystery_knight_desc}Hidden behind an unknown device and a closed helm, you defied custom and entered the lists. Whatever the heralds guessed, your courage and skill could not be dismissed."), (args, u) => { u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance); args.SetRenownToAdd(20); }, ccm => IsStormlander(ccm) && (CharacterObject.PlayerCharacter.IsFemale && NarrativeChoiceState.YouthWas("stormlander_youth_rebellious_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_fierce"));
        yield return new NarrativeOption("stormlander_adulthood_campaign_option", new TextObject("{=bab_stormlander_adulthood_campaign_title}you distinguished yourself during a local campaign."), new TextObject("{=bab_stormlander_adulthood_campaign_desc}When banners were called in the stormlands, you marched with the host and kept your courage when scouting, skirmishing, and hard close fighting replaced youthful drills."), (args, u) => { u.UpgradeLeadershipTacticsSkills(args, DefaultCharacterAttributes.Cunning); args.SetRenownToAdd(15); }, ccm => IsStormlander(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && NarrativeChoiceState.YouthWas("stormlander_youth_levy_option", "stormlander_youth_scout_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_drafted_to_war_pose"));
        yield return new NarrativeOption("stormlander_adulthood_court_service_option", new TextObject("{=bab_stormlander_adulthood_court_service_title}you won influence in a great household."), new TextObject("{=bab_stormlander_adulthood_court_service_desc}Your judgment, discretion, and command of household politics earned you trust in the rain-beaten keeps of the storm lords, and people began seeking your help before presenting delicate requests."), (args, u) => { u.UpgradeStewardCharmSkills(args, DefaultCharacterAttributes.Social); args.SetRenownToAdd(10); }, ccm => IsStormlander(ccm) && (NarrativeChoiceState.YouthWas("stormlander_youth_courtier_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_manners"));
        yield return new NarrativeOption("stormlander_adulthood_trade_venture_option", new TextObject("{=bab_stormlander_adulthood_trade_venture_title}you completed a profitable trading venture."), new TextObject("{=bab_stormlander_adulthood_trade_venture_desc}You organized credit, guards, transport, and buyers for a venture through stormland ports and castle storehouses, returning with both profit and a reputation for sound judgment."), (args, u) => { u.UpgradeTradeLeadershipSkills(args, DefaultCharacterAttributes.Intelligence); args.SetRenownToAdd(10); }, ccm => IsStormlander(ccm) && (NarrativeChoiceState.YouthWas("stormlander_youth_factor_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_decisive"));
        yield return new NarrativeOption("stormlander_adulthood_border_deed_option", new TextObject("{=bab_stormlander_adulthood_border_deed_title}you protected travellers from outlaws."), new TextObject("{=bab_stormlander_adulthood_border_deed_desc}Your knowledge of the rainwood, marches, and storm coast let you find an outlaw band that had preyed upon local travellers. You guided armed men to its camp and helped break it."), (args, u) => { u.UpgradeScoutingTacticsSkills(args, DefaultCharacterAttributes.Cunning); args.SetRenownToAdd(10); }, ccm => IsStormlander(ccm) && (NarrativeChoiceState.YouthWas("stormlander_youth_scout_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_tough"));
    }

    private static bool IsStormlander(CharacterCreationManager ccm) => ccm.CharacterCreationContent.SelectedCulture.StringId == "stormlander";

    private static NarrativeOption CreateParentOption(string id, string titleText, string descriptionText, System.Action<NarrativeMenuOptionArgs, NarrativeSkillUpgrades> setArgs, string occupationType, string motherAnimation, string fatherAnimation)
    {
        return new NarrativeOption(id, new TextObject(titleText), new TextObject(descriptionText), setArgs, IsStormlander, ccm =>
        {
            ccm.CharacterCreationContent.SetParentOccupation(occupationType);
            string cultureId = ccm.CharacterCreationContent.SelectedCulture.StringId;
            string motherEquipmentId = NarrativeEquipmentHelper.GetMotherEquipmentId(ccm, occupationType, cultureId);
            string fatherEquipmentId = NarrativeEquipmentHelper.GetFatherEquipmentId(ccm, occupationType, cultureId);
            NarrativeEquipmentHelper.SetParentEquipment(ccm, motherEquipmentId, fatherEquipmentId, motherAnimation, fatherAnimation);
        });
    }

    private void SelectYouth(CharacterCreationManager ccm, string titleType, string animation)
    {
        ccm.CharacterCreationContent.SelectedTitleType = titleType;
        string playerEquipmentId = NarrativeEquipmentHelper.GetPlayerEquipmentId(ccm, titleType, CultureId, Hero.MainHero.IsFemale);
        NarrativeEquipmentHelper.SetPlayerEquipment(ccm, playerEquipmentId, animation);
    }
}
