using System.Collections.Generic;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.CharacterCreationContent;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.Core;
using TaleWorlds.Localization;

namespace BloodAndBittersteel.Features.CharacterCreation.Cultures;

public class ValemanCulture : ICharacterCreationCulture
{
    public string CultureId => "valeman";

    public IEnumerable<NarrativeOption> GetParentOptions()
    {
        yield return CreateParentOption("valeman_retainer_option", "{=bab_crownlander_parent_retainer_title}A lord's retainers", "{=bab_valeman_parent_retainer_desc}Your family served in the household of a Vale lord, managing his estates and training the men who guarded his mountain roads and passes.", (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Social), CharacterOccupations.Retainer, "act_character_creation_female_default_side_to_side_1", "act_character_creation_male_default_side_to_side_1");
        yield return CreateParentOption("valeman_merchant_option", "{=651FhzdR}Urban merchants", "{=bab_valeman_parent_merchant_desc}Your family traded wool, grain, and mountain goods through the market towns and ports of the Vale.", (args, u) => u.UpgradeTradeCharmSkills(args, DefaultCharacterAttributes.Intelligence), CharacterOccupations.MerchantUrban, "act_character_creation_female_default_mother_front", "act_character_creation_male_default_mother_front");
        yield return CreateParentOption("valeman_farmer_option", "{=RDfXuVxT}Yeomen", "{=bab_valeman_parent_farmer_desc}Your family were free smallholders in one of the Vale's fertile valleys and answered their lord's call as part of the levy.", (args, u) => u.UpgradePolearmCrossbowSkills(args, DefaultCharacterAttributes.Endurance), CharacterOccupations.Farmer, "act_character_creation_female_default_father_sitting", "act_character_creation_male_default_father_sitting");
        yield return CreateParentOption("valeman_blacksmith_option", "{=p2KIhGbE}Urban blacksmith", "{=bab_valeman_parent_blacksmith_desc}Your family kept a smithy in a Vale town, shoeing horses and forging tools, mail, and weapons for the local garrison.", (args, u) => u.UpgradeCraftingTwoHandedSkills(args, DefaultCharacterAttributes.Vigor), CharacterOccupations.ArtisanUrban, "act_character_creation_female_default_side_to_side_2", "act_character_creation_male_default_side_to_side_2");
        yield return CreateParentOption("valeman_hunter_option", "{=YcnK0Thk}Hunters", "{=bab_valeman_parent_hunter_desc}Your family hunted the wooded slopes and high valleys, learning the hidden paths beneath the Mountains of the Moon.", (args, u) => u.UpgradeScoutingCrossbowSkills(args, DefaultCharacterAttributes.Control), CharacterOccupations.Hunter, "act_character_creation_female_default_side_to_side_3", "act_character_creation_male_default_side_to_side_3");
    }

    public IEnumerable<NarrativeOption> GetChildhoodOptions()
    {
        foreach (NarrativeOption option in MainlandChildhoodOptions.Shared)
            yield return option;

        yield return new NarrativeOption("valeman_childhood_mountain_climber_option", new TextObject("{=bab_valeman_childhood_mountain_climber_title}scrambled along the mountain paths."), new TextObject("{=bab_valeman_childhood_mountain_climber_desc}You raced other children over steep paths and broken slopes, learning balance, endurance, and respect for sudden mountain weather."), (args, u) => u.UpgradeAthleticsThrowingSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsValeman(ccm), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_childhood_character", "act_childhood_athlete"));
    }

    public IEnumerable<NarrativeOption> GetEducationOptions()
    {
        foreach (NarrativeOption option in MainlandEducationOptions.Shared)
            yield return option;

        yield return new NarrativeOption("valeman_education_mountain_page_option", new TextObject("{=bab_valeman_education_mountain_page_title}served as a page in a mountain keep."), new TextObject("{=bab_valeman_education_mountain_page_desc}You were fostered in a high Vale keep, learning courtesy in the hall and discipline from knights who guarded the narrow roads and mountain passes."), (args, u) => u.UpgradeLeadershipTacticsSkills(args, DefaultCharacterAttributes.Social), ccm => IsValeman(ccm) && ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer && !CharacterObject.PlayerCharacter.IsFemale, ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_manners", "", ""));
        yield return new NarrativeOption("valeman_education_mountain_lady_option", new TextObject("{=bab_valeman_education_mountain_lady_title}attended a lady of the Vale."), new TextObject("{=bab_valeman_education_mountain_lady_desc}You joined a noble household as a companion and attendant, learning letters, estate management, courtly manners, and the obligations joining the Vale's great families."), (args, u) => u.UpgradeStewardCharmSkills(args, DefaultCharacterAttributes.Social), ccm => IsValeman(ccm) && ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer && CharacterObject.PlayerCharacter.IsFemale, ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_manners", "", ""));
        yield return new NarrativeOption("valeman_education_mountain_paths_option", new TextObject("{=bab_valeman_education_mountain_paths_title}learned the high paths."), new TextObject("{=bab_valeman_education_mountain_paths_desc}You travelled with hunters, shepherds, and guides who taught you to read sudden weather, find shelter, and choose safe paths beneath the Mountains of the Moon."), (args, u) => u.UpgradeScoutingTacticsSkills(args, DefaultCharacterAttributes.Cunning), ccm => IsValeman(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Hunter), ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_fox", "", ""));
    }

    public IEnumerable<NarrativeOption> GetYouthOptions()
    {
        foreach (NarrativeOption option in WesterosiSharedPathOptions.YouthOptions)
            yield return option;

        yield return new NarrativeOption("valeman_youth_pack_mules_option", new TextObject("{=bab_valeman_youth_pack_mules_title}led pack mules along the high road."), new TextObject("{=bab_valeman_youth_pack_mules_desc}You learned every steep turn, shrine, inn, and shelter between the Gates of the Moon and the mountain valleys while coaxing laden mules over dangerous ground."), (args, u) => u.UpgradeScoutingRidingSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsValeman(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.MerchantUrban || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Hunter), ccm => SelectYouth(ccm, "merchant", "act_childhood_fox"));

        yield return new NarrativeOption("valeman_youth_squire_option", new TextObject("{=bab_valeman_youth_squire_title}served a knight as page and squire."), new TextObject("{=bab_valeman_youth_squire_desc}Through your family's service you entered the courts of the Eyrie and its bannermen, carrying messages, tending horses and harness, and training beneath an experienced knight."), (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsValeman(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer || NarrativeChoiceState.ChildhoodWas("childhood_horse_option", "valeman_childhood_mountain_climber_option") || NarrativeChoiceState.EducationWas("valeman_education_mountain_page_option"))), ccm => SelectYouth(ccm, "noble", "act_childhood_apprentice"));
        yield return new NarrativeOption("valeman_youth_levy_option", new TextObject("{=bab_valeman_youth_levy_title}trained with the local levy."), new TextObject("{=bab_valeman_youth_levy_desc}You drilled with the spears, shields, and bows used by the smallfolk of the Vale, learning to hold formation when fear and noise broke less disciplined ranks."), (args, u) => u.UpgradePolearmOneHandedSkills(args, DefaultCharacterAttributes.Vigor), ccm => IsValeman(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban || NarrativeChoiceState.ChildhoodWas("childhood_brawn_option"))), ccm => SelectYouth(ccm, "infantry", "act_childhood_fierce"));
        yield return new NarrativeOption("valeman_youth_scout_option", new TextObject("{=bab_valeman_youth_scout_title}ranged ahead of travellers and hunting parties."), new TextObject("{=bab_valeman_youth_scout_desc}Your knowledge of high roads and mountain passes made you useful as a guide and scout, watching for broken tracks, hostile riders, and safe ground ahead."), (args, u) => u.UpgradeScoutingBowSkills(args, DefaultCharacterAttributes.Cunning), ccm => IsValeman(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Hunter || NarrativeChoiceState.ChildhoodWas("childhood_detail_option", "valeman_childhood_mountain_climber_option")), ccm => SelectYouth(ccm, "skirmisher", "act_childhood_fox"));
        yield return new NarrativeOption("valeman_youth_courtier_option", new TextObject("{=bab_valeman_youth_courtier_title}learned to survive the intrigues of a noble court."), new TextObject("{=bab_valeman_youth_courtier_desc}You remained among the courts of the Eyrie and its bannermen, mastering household accounts, correspondence, courtesy, and the alliances hidden beneath feasts and ceremonies."), (args, u) => u.UpgradeStewardCharmSkills(args, DefaultCharacterAttributes.Social), ccm => IsValeman(ccm) && (CharacterObject.PlayerCharacter.IsFemale && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer || NarrativeChoiceState.EducationWas("education_retainer_lady_option", "valeman_education_mountain_lady_option"))), ccm => SelectYouth(ccm, "noble", "act_childhood_manners"));
        yield return new NarrativeOption("valeman_youth_factor_option", new TextObject("{=bab_valeman_youth_factor_title}acted as a young factor for your family."), new TextObject("{=bab_valeman_youth_factor_desc}You travelled through Gulltown and the Vale's guarded roads, inspecting goods, keeping accounts, and bargaining with people who respected profit more than birth."), (args, u) => u.UpgradeTradeCharmSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsValeman(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.MerchantUrban || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer), ccm => SelectYouth(ccm, "merchant", "act_childhood_book"));
        yield return new NarrativeOption("valeman_youth_rebellious_option", new TextObject("{=bab_valeman_youth_rebellious_title}trained secretly with horse and arms."), new TextObject("{=bab_valeman_youth_rebellious_desc}The customs of the Vale did not expect you to become a warrior. You borrowed time, weapons, and instruction wherever you could, refusing to let that judgment decide your life."), (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsValeman(ccm) && (CharacterObject.PlayerCharacter.IsFemale && (NarrativeChoiceState.ChildhoodWas("childhood_brawn_option", "childhood_horse_option", "valeman_childhood_mountain_climber_option") || NarrativeChoiceState.EducationWas("education_retainer_stables_option"))), ccm => SelectYouth(ccm, "cavalry", "act_childhood_fierce"));
    }

    public IEnumerable<NarrativeOption> GetAdulthoodOptions()
    {
        foreach (NarrativeOption option in WesterosiSharedPathOptions.AdulthoodOptions)
            yield return option;

        yield return new NarrativeOption("valeman_adulthood_road_inn_option", new TextObject("{=bab_valeman_adulthood_road_inn_title}you served inns and shrines upon the mountain road."), new TextObject("{=bab_valeman_adulthood_road_inn_desc}You carried news and provisions between lonely shrines and fortified inns, helping stranded pilgrims and keeping travellers moving when snow or rockfall closed the high road."), (args, u) => { u.UpgradeStewardCharmSkills(args, DefaultCharacterAttributes.Social); args.SetRenownToAdd(5); }, ccm => IsValeman(ccm) && NarrativeChoiceState.YouthWas("valeman_youth_pack_mules_option", "westerosi_youth_caravan_hand_option", "westerosi_youth_road_wanderer_option"), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_manners"));

        yield return new NarrativeOption("valeman_adulthood_tourney_knight_option", new TextObject("{=bab_valeman_adulthood_tourney_knight_title}you travelled the tourney circuit as a knight."), new TextObject("{=bab_valeman_adulthood_tourney_knight_desc}With horse, armour, and hard-won skill, you rode from one tourney in Westeros to the next, testing yourself in melees and lists while seeking ransom, patronage, and renown."), (args, u) => { u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance); args.SetRenownToAdd(20); }, ccm => IsValeman(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && NarrativeChoiceState.YouthWas("valeman_youth_squire_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_apprentice"));
        yield return new NarrativeOption("valeman_adulthood_mystery_knight_option", new TextObject("{=bab_valeman_adulthood_mystery_knight_title}you entered the lists as a mystery knight."), new TextObject("{=bab_valeman_adulthood_mystery_knight_desc}Hidden behind an unknown device and a closed helm, you defied custom and entered the lists. Whatever the heralds guessed, your courage and skill could not be dismissed."), (args, u) => { u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance); args.SetRenownToAdd(20); }, ccm => IsValeman(ccm) && (CharacterObject.PlayerCharacter.IsFemale && NarrativeChoiceState.YouthWas("valeman_youth_rebellious_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_fierce"));
        yield return new NarrativeOption("valeman_adulthood_campaign_option", new TextObject("{=bab_valeman_adulthood_campaign_title}you distinguished yourself during a local campaign."), new TextObject("{=bab_valeman_adulthood_campaign_desc}When banners were called in the Vale, you marched with the host and kept your courage when scouting, skirmishing, and hard close fighting replaced youthful drills."), (args, u) => { u.UpgradeLeadershipTacticsSkills(args, DefaultCharacterAttributes.Cunning); args.SetRenownToAdd(15); }, ccm => IsValeman(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && NarrativeChoiceState.YouthWas("valeman_youth_levy_option", "valeman_youth_scout_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_drafted_to_war_pose"));
        yield return new NarrativeOption("valeman_adulthood_court_service_option", new TextObject("{=bab_valeman_adulthood_court_service_title}you won influence in a great household."), new TextObject("{=bab_valeman_adulthood_court_service_desc}Your judgment, discretion, and command of household politics earned you trust in the courts of the Eyrie and its bannermen, and people began seeking your help before presenting delicate requests."), (args, u) => { u.UpgradeStewardCharmSkills(args, DefaultCharacterAttributes.Social); args.SetRenownToAdd(10); }, ccm => IsValeman(ccm) && (NarrativeChoiceState.YouthWas("valeman_youth_courtier_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_manners"));
        yield return new NarrativeOption("valeman_adulthood_trade_venture_option", new TextObject("{=bab_valeman_adulthood_trade_venture_title}you completed a profitable trading venture."), new TextObject("{=bab_valeman_adulthood_trade_venture_desc}You organized credit, guards, transport, and buyers for a venture through Gulltown and the Vale's guarded roads, returning with both profit and a reputation for sound judgment."), (args, u) => { u.UpgradeTradeLeadershipSkills(args, DefaultCharacterAttributes.Intelligence); args.SetRenownToAdd(10); }, ccm => IsValeman(ccm) && (NarrativeChoiceState.YouthWas("valeman_youth_factor_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_decisive"));
        yield return new NarrativeOption("valeman_adulthood_border_deed_option", new TextObject("{=bab_valeman_adulthood_border_deed_title}you protected travellers from outlaws."), new TextObject("{=bab_valeman_adulthood_border_deed_desc}Your knowledge of high roads and mountain passes let you find an outlaw band that had preyed upon local travellers. You guided armed men to its camp and helped break it."), (args, u) => { u.UpgradeScoutingTacticsSkills(args, DefaultCharacterAttributes.Cunning); args.SetRenownToAdd(10); }, ccm => IsValeman(ccm) && (NarrativeChoiceState.YouthWas("valeman_youth_scout_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_tough"));
    }

    private static bool IsValeman(CharacterCreationManager ccm) => ccm.CharacterCreationContent.SelectedCulture.StringId == "valeman";

    private static NarrativeOption CreateParentOption(string id, string titleText, string descriptionText, System.Action<NarrativeMenuOptionArgs, NarrativeSkillUpgrades> setArgs, string occupationType, string motherAnimation, string fatherAnimation)
    {
        return new NarrativeOption(id, new TextObject(titleText), new TextObject(descriptionText), setArgs, IsValeman, ccm =>
        {
            ccm.CharacterCreationContent.SetParentOccupation(occupationType);
            string cultureId = ccm.CharacterCreationContent.SelectedCulture.StringId;
            string motherEquipmentId = NarrativeEquipmentHelper.GetMotherEquipmentId(ccm, occupationType, cultureId);
            string fatherEquipmentId = NarrativeEquipmentHelper.GetFatherEquipmentId(ccm, occupationType, cultureId);
            NarrativeEquipmentHelper.SetParentEquipment(ccm, motherEquipmentId, fatherEquipmentId, motherAnimation, fatherAnimation);
        });
    }

    private void SelectYouth(CharacterCreationManager ccm, string titleType, string animation)
    {
        ccm.CharacterCreationContent.SelectedTitleType = titleType;
        string playerEquipmentId = NarrativeEquipmentHelper.GetPlayerEquipmentId(ccm, titleType, CultureId, Hero.MainHero.IsFemale);
        NarrativeEquipmentHelper.SetPlayerEquipment(ccm, playerEquipmentId, animation);
    }
}
