using System.Collections.Generic;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.CharacterCreationContent;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.Core;
using TaleWorlds.Localization;

namespace BloodAndBittersteel.Features.CharacterCreation.Cultures;

public class WesterlanderCulture : ICharacterCreationCulture
{
    public string CultureId => "westerlander";

    public IEnumerable<NarrativeOption> GetParentOptions()
    {
        yield return CreateParentOption("westerlander_retainer_option", "{=bab_crownlander_parent_retainer_title}A lord's retainers", "{=bab_westerlander_parent_retainer_desc}Your family served a Westerlands lord, supervising mines, estates, and tenants while helping train his household levy.", (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Social), CharacterOccupations.Retainer, "act_character_creation_female_default_side_to_side_1", "act_character_creation_male_default_side_to_side_1");
        yield return CreateParentOption("westerlander_merchant_option", "{=651FhzdR}Urban merchants", "{=bab_westerlander_parent_merchant_desc}Your family traded ore, metalwork, wool, and luxury goods through the wealthy towns of the Westerlands.", (args, u) => u.UpgradeTradeCharmSkills(args, DefaultCharacterAttributes.Intelligence), CharacterOccupations.MerchantUrban, "act_character_creation_female_default_mother_front", "act_character_creation_male_default_mother_front");
        yield return CreateParentOption("westerlander_farmer_option", "{=RDfXuVxT}Yeomen", "{=bab_westerlander_parent_farmer_desc}Your family held a modest farm among rocky hills and fertile valleys, owing service to a powerful local lord.", (args, u) => u.UpgradePolearmCrossbowSkills(args, DefaultCharacterAttributes.Endurance), CharacterOccupations.Farmer, "act_character_creation_female_default_father_sitting", "act_character_creation_male_default_father_sitting");
        yield return CreateParentOption("westerlander_blacksmith_option", "{=p2KIhGbE}Urban blacksmith", "{=bab_westerlander_parent_blacksmith_desc}Your family worked metal in a prosperous town, with fine ore and wealthy patrons bringing steady custom to the forge.", (args, u) => u.UpgradeCraftingTwoHandedSkills(args, DefaultCharacterAttributes.Vigor), CharacterOccupations.ArtisanUrban, "act_character_creation_female_default_side_to_side_2", "act_character_creation_male_default_side_to_side_2");
        yield return CreateParentOption("westerlander_hunter_option", "{=YcnK0Thk}Hunters", "{=bab_westerlander_parent_hunter_desc}Your family hunted the wooded hills, trapped valuable pelts, and learned the forgotten tracks between mines and keeps.", (args, u) => u.UpgradeScoutingCrossbowSkills(args, DefaultCharacterAttributes.Control), CharacterOccupations.Hunter, "act_character_creation_female_default_side_to_side_3", "act_character_creation_male_default_side_to_side_3");
    }

    public IEnumerable<NarrativeOption> GetChildhoodOptions()
    {
        foreach (NarrativeOption option in MainlandChildhoodOptions.Shared)
            yield return option;

        yield return new NarrativeOption("westerlander_childhood_mine_tales_option", new TextObject("{=bab_westerlander_childhood_mine_tales_title}explored the old workings and spoil heaps."), new TextObject("{=bab_westerlander_childhood_mine_tales_desc}You searched discarded stone for bright traces of ore and listened to miners describe the dangers and hidden wealth beneath the hills."), (args, u) => u.UpgradeCraftingEngineeringSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsWesterlander(ccm), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_childhood_character", "act_childhood_memory"));
    }

    public IEnumerable<NarrativeOption> GetEducationOptions()
    {
        foreach (NarrativeOption option in MainlandEducationOptions.Shared)
            yield return option;

        yield return new NarrativeOption("westerlander_education_mine_accounts_option", new TextObject("{=bab_westerlander_education_mine_accounts_title}kept accounts for mines and metal traders."), new TextObject("{=bab_westerlander_education_mine_accounts_desc}You recorded ore, wages, timber, tools, and shipments, learning how the wealth beneath the hills passed through many hands before becoming coin."), (args, u) => u.UpgradeEngineeringTradeSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsWesterlander(ccm) && ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.MerchantUrban, ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_book", "", ""));
        yield return new NarrativeOption("westerlander_education_goldsmith_option", new TextObject("{=bab_westerlander_education_goldsmith_title}trained with the metalworkers of the west."), new TextObject("{=bab_westerlander_education_goldsmith_desc}You learned to judge ore and alloys and watched skilled hands turn the wealth of the hills into tools, fittings, bright plate, and delicate goldwork."), (args, u) => u.UpgradeTradeCraftingSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsWesterlander(ccm) && ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban, ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_grit", "", ""));
        yield return new NarrativeOption("westerlander_education_rock_court_option", new TextObject("{=bab_westerlander_education_rock_court_title}were fostered in a wealthy court."), new TextObject("{=bab_westerlander_education_rock_court_desc}You entered the household of a powerful lord, where strict ceremony, careful accounts, and the ambitions of richly armed retainers taught you how power was displayed and preserved."), (args, u) => u.UpgradeLeadershipCharmSkills(args, DefaultCharacterAttributes.Social), ccm => IsWesterlander(ccm) && ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer, ccm => MainlandEducationOptions.SetEducationAnim(ccm, "act_childhood_manners", "", ""));
    }

    public IEnumerable<NarrativeOption> GetYouthOptions()
    {
        foreach (NarrativeOption option in WesterosiSharedPathOptions.YouthOptions)
            yield return option;

        yield return new NarrativeOption("westerlander_youth_squire_option", new TextObject("{=bab_westerlander_youth_squire_title}served a knight as page and squire."), new TextObject("{=bab_westerlander_youth_squire_desc}Through your family's service you entered the wealthy courts beneath Casterly Rock, carrying messages, tending horses and harness, and training beneath an experienced knight."), (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsWesterlander(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer || NarrativeChoiceState.ChildhoodWas("childhood_horse_option", "westerlander_childhood_mine_tales_option") || NarrativeChoiceState.EducationWas("westerlander_education_rock_court_option"))), ccm => SelectYouth(ccm, "noble", "act_childhood_apprentice"));
        yield return new NarrativeOption("westerlander_youth_levy_option", new TextObject("{=bab_westerlander_youth_levy_title}trained with the local levy."), new TextObject("{=bab_westerlander_youth_levy_desc}You drilled with the spears, shields, and bows used by the smallfolk of the westerlands, learning to hold formation when fear and noise broke less disciplined ranks."), (args, u) => u.UpgradePolearmOneHandedSkills(args, DefaultCharacterAttributes.Vigor), ccm => IsWesterlander(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban || NarrativeChoiceState.ChildhoodWas("childhood_brawn_option"))), ccm => SelectYouth(ccm, "infantry", "act_childhood_fierce"));
        yield return new NarrativeOption("westerlander_youth_scout_option", new TextObject("{=bab_westerlander_youth_scout_title}ranged ahead of travellers and hunting parties."), new TextObject("{=bab_westerlander_youth_scout_desc}Your knowledge of wooded hills, mines, and fortified roads made you useful as a guide and scout, watching for broken tracks, hostile riders, and safe ground ahead."), (args, u) => u.UpgradeScoutingBowSkills(args, DefaultCharacterAttributes.Cunning), ccm => IsWesterlander(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Hunter || NarrativeChoiceState.ChildhoodWas("childhood_detail_option", "westerlander_childhood_mine_tales_option")), ccm => SelectYouth(ccm, "skirmisher", "act_childhood_fox"));
        yield return new NarrativeOption("westerlander_youth_courtier_option", new TextObject("{=bab_westerlander_youth_courtier_title}learned to survive the intrigues of a noble court."), new TextObject("{=bab_westerlander_youth_courtier_desc}You remained among the wealthy courts beneath Casterly Rock, mastering household accounts, correspondence, courtesy, and the alliances hidden beneath feasts and ceremonies."), (args, u) => u.UpgradeStewardCharmSkills(args, DefaultCharacterAttributes.Social), ccm => IsWesterlander(ccm) && (CharacterObject.PlayerCharacter.IsFemale && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Retainer || NarrativeChoiceState.EducationWas("education_retainer_lady_option"))), ccm => SelectYouth(ccm, "noble", "act_childhood_manners"));
        yield return new NarrativeOption("westerlander_youth_factor_option", new TextObject("{=bab_westerlander_youth_factor_title}acted as a young factor for your family."), new TextObject("{=bab_westerlander_youth_factor_desc}You travelled through Lannisport and the gold and silver trade, inspecting goods, keeping accounts, and bargaining with people who respected profit more than birth."), (args, u) => u.UpgradeTradeCharmSkills(args, DefaultCharacterAttributes.Intelligence), ccm => IsWesterlander(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.MerchantUrban || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.Farmer), ccm => SelectYouth(ccm, "merchant", "act_childhood_book"));
        yield return new NarrativeOption("westerlander_youth_rebellious_option", new TextObject("{=bab_westerlander_youth_rebellious_title}trained secretly with horse and arms."), new TextObject("{=bab_westerlander_youth_rebellious_desc}The customs of the westerlands did not expect you to become a warrior. You borrowed time, weapons, and instruction wherever you could, refusing to let that judgment decide your life."), (args, u) => u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance), ccm => IsWesterlander(ccm) && (CharacterObject.PlayerCharacter.IsFemale && (NarrativeChoiceState.ChildhoodWas("childhood_brawn_option", "childhood_horse_option", "westerlander_childhood_mine_tales_option") || NarrativeChoiceState.EducationWas("education_retainer_stables_option"))), ccm => SelectYouth(ccm, "cavalry", "act_childhood_fierce"));
    }

    public IEnumerable<NarrativeOption> GetAdulthoodOptions()
    {
        foreach (NarrativeOption option in WesterosiSharedPathOptions.AdulthoodOptions)
            yield return option;

        yield return new NarrativeOption("westerlander_adulthood_ore_smithy_option", new TextObject("{=bab_westerlander_adulthood_ore_smithy_title}you supplied smithies from mine to market."), new TextObject("{=bab_westerlander_adulthood_ore_smithy_desc}You arranged ore carts, charcoal, tools, and skilled hands between the western mines and their smithies, learning how wealth depended upon labor done far from any golden hall."), (args, u) => { u.UpgradeTradeCraftingSkills(args, DefaultCharacterAttributes.Intelligence); args.SetRenownToAdd(10); }, ccm => IsWesterlander(ccm) && (ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.ArtisanUrban || ccm.CharacterCreationContent.SelectedParentOccupation == CharacterOccupations.MerchantUrban || NarrativeChoiceState.YouthWas("westerosi_youth_family_workshop_option", "westerosi_youth_itinerant_craft_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_grit"));

        yield return new NarrativeOption("westerlander_adulthood_tourney_knight_option", new TextObject("{=bab_westerlander_adulthood_tourney_knight_title}you travelled the tourney circuit as a knight."), new TextObject("{=bab_westerlander_adulthood_tourney_knight_desc}With horse, armour, and hard-won skill, you rode from one tourney in Westeros to the next, testing yourself in melees and lists while seeking ransom, patronage, and renown."), (args, u) => { u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance); args.SetRenownToAdd(20); }, ccm => IsWesterlander(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && NarrativeChoiceState.YouthWas("westerlander_youth_squire_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_apprentice"));
        yield return new NarrativeOption("westerlander_adulthood_mystery_knight_option", new TextObject("{=bab_westerlander_adulthood_mystery_knight_title}you entered the lists as a mystery knight."), new TextObject("{=bab_westerlander_adulthood_mystery_knight_desc}Hidden behind an unknown device and a closed helm, you defied custom and entered the lists. Whatever the heralds guessed, your courage and skill could not be dismissed."), (args, u) => { u.UpgradeRidingPolearmSkills(args, DefaultCharacterAttributes.Endurance); args.SetRenownToAdd(20); }, ccm => IsWesterlander(ccm) && (CharacterObject.PlayerCharacter.IsFemale && NarrativeChoiceState.YouthWas("westerlander_youth_rebellious_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_fierce"));
        yield return new NarrativeOption("westerlander_adulthood_campaign_option", new TextObject("{=bab_westerlander_adulthood_campaign_title}you distinguished yourself during a local campaign."), new TextObject("{=bab_westerlander_adulthood_campaign_desc}When banners were called in the westerlands, you marched with the host and kept your courage when scouting, skirmishing, and hard close fighting replaced youthful drills."), (args, u) => { u.UpgradeLeadershipTacticsSkills(args, DefaultCharacterAttributes.Cunning); args.SetRenownToAdd(15); }, ccm => IsWesterlander(ccm) && (!CharacterObject.PlayerCharacter.IsFemale && NarrativeChoiceState.YouthWas("westerlander_youth_levy_option", "westerlander_youth_scout_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_drafted_to_war_pose"));
        yield return new NarrativeOption("westerlander_adulthood_court_service_option", new TextObject("{=bab_westerlander_adulthood_court_service_title}you won influence in a great household."), new TextObject("{=bab_westerlander_adulthood_court_service_desc}Your judgment, discretion, and command of household politics earned you trust in the wealthy courts beneath Casterly Rock, and people began seeking your help before presenting delicate requests."), (args, u) => { u.UpgradeStewardCharmSkills(args, DefaultCharacterAttributes.Social); args.SetRenownToAdd(10); }, ccm => IsWesterlander(ccm) && (NarrativeChoiceState.YouthWas("westerlander_youth_courtier_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_manners"));
        yield return new NarrativeOption("westerlander_adulthood_trade_venture_option", new TextObject("{=bab_westerlander_adulthood_trade_venture_title}you completed a profitable trading venture."), new TextObject("{=bab_westerlander_adulthood_trade_venture_desc}You organized credit, guards, transport, and buyers for a venture through Lannisport and the gold and silver trade, returning with both profit and a reputation for sound judgment."), (args, u) => { u.UpgradeTradeLeadershipSkills(args, DefaultCharacterAttributes.Intelligence); args.SetRenownToAdd(10); }, ccm => IsWesterlander(ccm) && (NarrativeChoiceState.YouthWas("westerlander_youth_factor_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_decisive"));
        yield return new NarrativeOption("westerlander_adulthood_border_deed_option", new TextObject("{=bab_westerlander_adulthood_border_deed_title}you protected travellers from outlaws."), new TextObject("{=bab_westerlander_adulthood_border_deed_desc}Your knowledge of wooded hills, mines, and fortified roads let you find an outlaw band that had preyed upon local travellers. You guided armed men to its camp and helped break it."), (args, u) => { u.UpgradeScoutingTacticsSkills(args, DefaultCharacterAttributes.Cunning); args.SetRenownToAdd(10); }, ccm => IsWesterlander(ccm) && (NarrativeChoiceState.YouthWas("westerlander_youth_scout_option")), ccm => NarrativeEquipmentHelper.SetPlayerCharacterAnimation(ccm, "player_adulthood_character", "act_childhood_tough"));
    }

    private static bool IsWesterlander(CharacterCreationManager ccm) => ccm.CharacterCreationContent.SelectedCulture.StringId == "westerlander";

    private static NarrativeOption CreateParentOption(string id, string titleText, string descriptionText, System.Action<NarrativeMenuOptionArgs, NarrativeSkillUpgrades> setArgs, string occupationType, string motherAnimation, string fatherAnimation)
    {
        return new NarrativeOption(id, new TextObject(titleText), new TextObject(descriptionText), setArgs, IsWesterlander, ccm =>
        {
            ccm.CharacterCreationContent.SetParentOccupation(occupationType);
            string cultureId = ccm.CharacterCreationContent.SelectedCulture.StringId;
            string motherEquipmentId = NarrativeEquipmentHelper.GetMotherEquipmentId(ccm, occupationType, cultureId);
            string fatherEquipmentId = NarrativeEquipmentHelper.GetFatherEquipmentId(ccm, occupationType, cultureId);
            NarrativeEquipmentHelper.SetParentEquipment(ccm, motherEquipmentId, fatherEquipmentId, motherAnimation, fatherAnimation);
        });
    }

    private void SelectYouth(CharacterCreationManager ccm, string titleType, string animation)
    {
        ccm.CharacterCreationContent.SelectedTitleType = titleType;
        string playerEquipmentId = NarrativeEquipmentHelper.GetPlayerEquipmentId(ccm, titleType, CultureId, Hero.MainHero.IsFemale);
        NarrativeEquipmentHelper.SetPlayerEquipment(ccm, playerEquipmentId, animation);
    }
}
