<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Version>0.0.1</Version>
		<TargetFramework>net472</TargetFramework>
		<Platforms>x64</Platforms>
		<LangVersion>10.0</LangVersion>
		<Nullable>enable</Nullable>
		<ModuleId>$(MSBuildProjectName)</ModuleId>
		<ModuleName>$(MSBuildProjectName)</ModuleName>
		<GameFolder>$(BANNERLORD_GAME_DIR)</GameFolder>
		<Configurations>Debug;Release;aaa;ccc</Configurations>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Bannerlord.MCM" Version="5.12.2" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="$(GameFolder)\bin\Win64_Shipping_Client\TaleWorlds.*.dll" Exclude="$(GameFolder)\bin\Win64_Shipping_Client\TaleWorlds.Native.dll">
			<HintPath>%(Identity)</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\LanceSystem\LanceSystem.csproj" />
	</ItemGroup>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="echo ProjectDir=$(ProjectDir)&#xD;&#xA;xcopy /y /d &quot;$(ProjectDir)\bin\x64\aaa\net472\LanceSystemMCMintegration.dll&quot; &quot;$(BANNERLORD_GAME_DIR)\Modules\BloodAndBittersteel\bin\Win64_Shipping_Client\&quot;&#xD;&#xA;" />
	</Target>
</Project>